// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCore.Modules.Payment.Infrastructure;

#nullable disable

namespace TravelCore.Modules.Payment.Infrastructure.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20260818170426_AddHotelBookingPaymentTarget")]
    partial class AddHotelBookingPaymentTarget
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payment")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelCore.Modules.Payment.Domain.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("Booking")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("HotelBooking")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_booking_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Instant>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.Property<Instant?>("SucceededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("succeeded_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Booking")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_booking_id")
                        .HasFilter("booking_id IS NOT NULL");

                    b.HasIndex("HotelBooking")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_hotel_booking_id")
                        .HasFilter("hotel_booking_id IS NOT NULL");

                    b.ToTable("payments", "payment", t =>
                        {
                            t.HasCheckConstraint("ck_payments_exactly_one_target", "(booking_id IS NOT NULL AND hotel_booking_id IS NULL) OR (booking_id IS NULL AND hotel_booking_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_payments_status", "status IN (1, 2)");

                            t.HasCheckConstraint("ck_payments_version_nonnegative", "version >= 0");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Payment.Domain.PaymentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("InitiatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("initiated_at");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderRequestReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_request_reference");

                    b.Property<string>("ProviderTransactionReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_transaction_reference");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Instant>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_attempts_one_active_per_payment")
                        .HasFilter("status IN (1, 2)");

                    b.HasIndex("ProviderKey", "ProviderRequestReference")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_attempts_provider_request")
                        .HasFilter("provider_key IS NOT NULL AND provider_request_reference IS NOT NULL");

                    b.HasIndex("ProviderKey", "ProviderTransactionReference")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_attempts_provider_transaction")
                        .HasFilter("provider_key IS NOT NULL AND provider_transaction_reference IS NOT NULL");

                    b.ToTable("payment_attempts", "payment", t =>
                        {
                            t.HasCheckConstraint("ck_payment_attempts_status", "status IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Payment.Domain.PaymentInitiationIdempotencyRecord", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("PaymentId", "IdempotencyKey");

                    b.HasIndex("AttemptId")
                        .HasDatabaseName("ix_payment_initiation_idempotency_attempt_id");

                    b.ToTable("payment_initiation_idempotency", "payment");
                });

            modelBuilder.Entity("TravelCore.Modules.Payment.Domain.PaymentReconciliationIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<Instant>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<Instant?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId")
                        .HasDatabaseName("ix_payment_reconciliation_issues_attempt_id");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("ix_payment_reconciliation_issues_payment_id");

                    b.ToTable("payment_reconciliation_issues", "payment", t =>
                        {
                            t.HasCheckConstraint("ck_payment_reconciliation_issues_kind", "kind IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Payment.Domain.Refund", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("Booking")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("HotelBooking")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_booking_id");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Instant>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.Property<Instant?>("SucceededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("succeeded_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .IsUnique()
                        .HasDatabaseName("ux_refunds_payment_id");

                    b.ToTable("refunds", "payment", t =>
                        {
                            t.HasCheckConstraint("ck_refunds_exactly_one_target", "(booking_id IS NOT NULL AND hotel_booking_id IS NULL) OR (booking_id IS NULL AND hotel_booking_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_refunds_status", "status IN (1, 2)");

                            t.HasCheckConstraint("ck_refunds_version_nonnegative", "version >= 0");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Payment.Domain.RefundAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("InitiatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("initiated_at");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderRequestReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_request_reference");

                    b.Property<string>("ProviderTransactionReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_transaction_reference");

                    b.Property<Guid>("RefundId")
                        .HasColumnType("uuid")
                        .HasColumnName("refund_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Instant>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.HasKey("Id");

                    b.HasIndex("RefundId")
                        .IsUnique()
                        .HasDatabaseName("ux_refund_attempts_one_active_per_refund")
                        .HasFilter("status IN (1, 2)");

                    b.HasIndex("ProviderKey", "ProviderRequestReference")
                        .IsUnique()
                        .HasDatabaseName("ux_refund_attempts_provider_request")
                        .HasFilter("provider_key IS NOT NULL AND provider_request_reference IS NOT NULL");

                    b.HasIndex("ProviderKey", "ProviderTransactionReference")
                        .IsUnique()
                        .HasDatabaseName("ux_refund_attempts_provider_transaction")
                        .HasFilter("provider_key IS NOT NULL AND provider_transaction_reference IS NOT NULL");

                    b.ToTable("refund_attempts", "payment", t =>
                        {
                            t.HasCheckConstraint("ck_refund_attempts_status", "status IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Payment.Domain.RefundReconciliationIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<Instant>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<Guid>("RefundId")
                        .HasColumnType("uuid")
                        .HasColumnName("refund_id");

                    b.Property<Instant?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId")
                        .HasDatabaseName("ix_refund_reconciliation_issues_attempt_id");

                    b.HasIndex("RefundId")
                        .HasDatabaseName("ix_refund_reconciliation_issues_refund_id");

                    b.ToTable("refund_reconciliation_issues", "payment", t =>
                        {
                            t.HasCheckConstraint("ck_refund_reconciliation_issues_kind", "kind IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Payment.Infrastructure.PaymentCompensationInboxRecord", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<Instant>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("PaymentId");

                    b.ToTable("compensation_inbox", "payment");
                });

            modelBuilder.Entity("TravelCore.Modules.Payment.Infrastructure.PaymentOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("message_type");

                    b.Property<Instant>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Instant?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_payment_outbox_messages_processed_at");

                    b.ToTable("outbox_messages", "payment");
                });

            modelBuilder.Entity("TravelCore.Modules.Payment.Domain.Payment", b =>
                {
                    b.OwnsOne("TravelCore.Modules.Payment.Domain.PaymentExecutionSnapshot", "ExecutionSnapshot", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("BookingSnapshotId")
                                .HasColumnType("uuid")
                                .HasColumnName("booking_snapshot_id");

                            b1.Property<Instant>("CapturedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("execution_captured_at");

                            b1.HasKey("PaymentId");

                            b1.ToTable("payments", "payment");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");

                            b1.OwnsOne("TravelCore.Money.Money", "Amount", b2 =>
                                {
                                    b2.Property<Guid>("PaymentExecutionSnapshotPaymentId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("execution_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("execution_currency");

                                    b2.HasKey("PaymentExecutionSnapshotPaymentId");

                                    b2.ToTable("payments", "payment");

                                    b2.WithOwner()
                                        .HasForeignKey("PaymentExecutionSnapshotPaymentId");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();
                        });

                    b.Navigation("ExecutionSnapshot");
                });

            modelBuilder.Entity("TravelCore.Modules.Payment.Domain.PaymentAttempt", b =>
                {
                    b.HasOne("TravelCore.Modules.Payment.Domain.Payment", null)
                        .WithMany("Attempts")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Payment.Domain.PaymentInitiationIdempotencyRecord", b =>
                {
                    b.HasOne("TravelCore.Modules.Payment.Domain.Payment", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Payment.Domain.PaymentReconciliationIssue", b =>
                {
                    b.HasOne("TravelCore.Modules.Payment.Domain.Payment", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Payment.Domain.Refund", b =>
                {
                    b.HasOne("TravelCore.Modules.Payment.Domain.Payment", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("TravelCore.Money.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("RefundId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("RefundId");

                            b1.ToTable("refunds", "payment");

                            b1.WithOwner()
                                .HasForeignKey("RefundId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Payment.Domain.RefundAttempt", b =>
                {
                    b.HasOne("TravelCore.Modules.Payment.Domain.Refund", null)
                        .WithMany("Attempts")
                        .HasForeignKey("RefundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Payment.Domain.RefundReconciliationIssue", b =>
                {
                    b.HasOne("TravelCore.Modules.Payment.Domain.Refund", null)
                        .WithMany()
                        .HasForeignKey("RefundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Payment.Domain.Payment", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("TravelCore.Modules.Payment.Domain.Refund", b =>
                {
                    b.Navigation("Attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
