// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCore.Modules.AgencyMarketplace.Infrastructure;

#nullable disable

namespace TravelCore.Modules.AgencyMarketplace.Infrastructure.Migrations
{
    [DbContext(typeof(AgencyMarketplaceDbContext))]
    [Migration("20260817150000_AddAgencyProfile")]
    partial class AddAgencyProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("agency_marketplace")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelCore.Modules.AgencyMarketplace.Domain.AgencyProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PartyId")
                        .IsUnique()
                        .HasDatabaseName("ux_agency_profiles_party_id");

                    b.ToTable("agency_profiles", "agency_marketplace");
                });

            modelBuilder.Entity("TravelCore.Modules.AgencyMarketplace.Domain.AgencyProfile", b =>
                {
                    b.OwnsOne("TravelCore.Modules.AgencyMarketplace.Domain.AgencyCommercialSettings", "Commercial", b1 =>
                        {
                            b1.Property<Guid>("AgencyProfileId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("PublicListingEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("public_listing_enabled");

                            b1.HasKey("AgencyProfileId");

                            b1.ToTable("agency_profiles", "agency_marketplace");

                            b1.WithOwner()
                                .HasForeignKey("AgencyProfileId");
                        });

                    b.OwnsOne("TravelCore.Modules.AgencyMarketplace.Domain.AgencyContactSettings", "Contact", b1 =>
                        {
                            b1.Property<Guid>("AgencyProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PublicEmail")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("public_email");

                            b1.Property<string>("PublicPhone")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("public_phone");

                            b1.Property<string>("WebsiteUrl")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("website_url");

                            b1.HasKey("AgencyProfileId");

                            b1.ToTable("agency_profiles", "agency_marketplace");

                            b1.WithOwner()
                                .HasForeignKey("AgencyProfileId");
                        });

                    b.OwnsOne("TravelCore.Modules.AgencyMarketplace.Domain.AgencyDisplayInfo", "Display", b1 =>
                        {
                            b1.Property<Guid>("AgencyProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("description");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("display_name");

                            b1.Property<Guid?>("LogoMediaAssetId")
                                .HasColumnType("uuid")
                                .HasColumnName("logo_media_asset_id");

                            b1.HasKey("AgencyProfileId");

                            b1.ToTable("agency_profiles", "agency_marketplace");

                            b1.WithOwner()
                                .HasForeignKey("AgencyProfileId");
                        });

                    b.Navigation("Commercial")
                        .IsRequired();

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("Display")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
