// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCore.Modules.Tour.Infrastructure;

#nullable disable

namespace TravelCore.Modules.Tour.Infrastructure.Migrations
{
    [DbContext(typeof(TourDbContext))]
    [Migration("20260817021000_AddTourProductTables")]
    partial class AddTourProductTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tour")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("english_name");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_tour_products_code");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_tour_products_created_at");

                    b.HasIndex("Kind")
                        .HasDatabaseName("ix_tour_products_kind");

                    b.ToTable("tour_products", "tour");
                });
#pragma warning restore 612, 618
        }
    }
}
