// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCore.Modules.Tour.Infrastructure;

#nullable disable

namespace TravelCore.Modules.Tour.Infrastructure.Migrations
{
    [DbContext(typeof(TourDbContext))]
    [Migration("20260817030000_AddExperienceItineraryStopSemanticLinks")]
    partial class AddExperienceItineraryStopSemanticLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tour")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.ExperienceItinerary", b =>
                {
                    b.Property<Guid>("TourProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("tour_product_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TourProductId");

                    b.ToTable("tour_experience_itineraries", "tour");
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.ExperienceItineraryDay", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer")
                        .HasColumnName("day_number");

                    b.Property<Guid>("TourProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("tour_product_id");

                    b.HasKey("Id");

                    b.HasIndex("TourProductId", "DayNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_tour_experience_itinerary_days_tour_day");

                    b.ToTable("tour_experience_itinerary_days", "tour");
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.ExperienceItineraryStop", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("DestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_id");

                    b.Property<Guid>("ItineraryDayId")
                        .HasColumnType("uuid")
                        .HasColumnName("itinerary_day_id");

                    b.Property<Guid?>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId")
                        .HasDatabaseName("ix_tour_experience_itinerary_stops_destination_id");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("ix_tour_experience_itinerary_stops_place_id");

                    b.HasIndex("ItineraryDayId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_tour_experience_itinerary_stops_day_sort");

                    b.ToTable("tour_experience_itinerary_stops", "tour");
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourExperienceSpecialization", b =>
                {
                    b.Property<Guid>("TourProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("tour_product_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TourProductId");

                    b.ToTable("tour_experience_specializations", "tour");
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<short>("CatalogStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("catalog_status");

                    b.Property<string>("ClassificationCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("classification_code");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("english_name");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<Guid?>("OriginDestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_destination_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_tour_products_agency_id");

                    b.HasIndex("CatalogStatus")
                        .HasDatabaseName("ix_tour_products_catalog_status");

                    b.HasIndex("ClassificationCode")
                        .HasDatabaseName("ix_tour_products_classification_code");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_tour_products_code");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_tour_products_created_at");

                    b.HasIndex("Kind")
                        .HasDatabaseName("ix_tour_products_kind");

                    b.HasIndex("OriginDestinationId")
                        .HasDatabaseName("ix_tour_products_origin_destination_id");

                    b.ToTable("tour_products", "tour");
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourProductDestination", b =>
                {
                    b.Property<Guid>("TourProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("tour_product_id");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_id");

                    b.HasKey("TourProductId", "DestinationId");

                    b.HasIndex("DestinationId")
                        .HasDatabaseName("ix_tour_product_destinations_destination_id");

                    b.ToTable("tour_product_destinations", "tour");
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourProductMediaLink", b =>
                {
                    b.Property<Guid>("TourProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("tour_product_id");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("TourProductId", "MediaAssetId");

                    b.HasIndex("MediaAssetId")
                        .HasDatabaseName("ix_tour_product_media_links_media_asset_id");

                    b.HasIndex("TourProductId")
                        .IsUnique()
                        .HasDatabaseName("ux_tour_product_media_links_cover")
                        .HasFilter("role = 0");

                    b.HasIndex("TourProductId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_tour_product_media_links_gallery_sort")
                        .HasFilter("role = 1");

                    b.ToTable("tour_product_media_links", "tour");
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourProductPolicy", b =>
                {
                    b.Property<Guid>("TourProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("tour_product_id");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Detail")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("detail");

                    b.HasKey("TourProductId", "Code");

                    b.ToTable("tour_product_policies", "tour");
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourProductRequirement", b =>
                {
                    b.Property<Guid>("TourProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("tour_product_id");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Detail")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("detail");

                    b.HasKey("TourProductId", "Code");

                    b.ToTable("tour_product_requirements", "tour");
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourProductService", b =>
                {
                    b.Property<Guid>("TourProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("tour_product_id");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Detail")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("detail");

                    b.HasKey("TourProductId", "Code");

                    b.ToTable("tour_product_services", "tour");
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourProductTranslation", b =>
                {
                    b.Property<Guid>("TourProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("tour_product_id");

                    b.Property<string>("LocaleCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale_code");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Slug")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TourProductId", "LocaleCode");

                    b.HasIndex("LocaleCode")
                        .HasDatabaseName("ix_tour_product_translations_locale_code");

                    b.HasIndex("LocaleCode", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_tour_product_translations_locale_slug")
                        .HasFilter("slug IS NOT NULL");

                    b.ToTable("tour_product_translations", "tour");
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.ExperienceItinerary", b =>
                {
                    b.HasOne("TravelCore.Modules.Tour.Domain.TourExperienceSpecialization", null)
                        .WithOne("Itinerary")
                        .HasForeignKey("TravelCore.Modules.Tour.Domain.ExperienceItinerary", "TourProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.ExperienceItineraryDay", b =>
                {
                    b.HasOne("TravelCore.Modules.Tour.Domain.ExperienceItinerary", null)
                        .WithMany("Days")
                        .HasForeignKey("TourProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.ExperienceItineraryStop", b =>
                {
                    b.HasOne("TravelCore.Modules.Tour.Domain.ExperienceItineraryDay", null)
                        .WithMany("Stops")
                        .HasForeignKey("ItineraryDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourExperienceSpecialization", b =>
                {
                    b.HasOne("TravelCore.Modules.Tour.Domain.TourProduct", null)
                        .WithOne()
                        .HasForeignKey("TravelCore.Modules.Tour.Domain.TourExperienceSpecialization", "TourProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourProductDestination", b =>
                {
                    b.HasOne("TravelCore.Modules.Tour.Domain.TourProduct", null)
                        .WithMany("Destinations")
                        .HasForeignKey("TourProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourProductMediaLink", b =>
                {
                    b.HasOne("TravelCore.Modules.Tour.Domain.TourProduct", null)
                        .WithMany("MediaLinks")
                        .HasForeignKey("TourProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourProductPolicy", b =>
                {
                    b.HasOne("TravelCore.Modules.Tour.Domain.TourProduct", null)
                        .WithMany("Policies")
                        .HasForeignKey("TourProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourProductRequirement", b =>
                {
                    b.HasOne("TravelCore.Modules.Tour.Domain.TourProduct", null)
                        .WithMany("Requirements")
                        .HasForeignKey("TourProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourProductService", b =>
                {
                    b.HasOne("TravelCore.Modules.Tour.Domain.TourProduct", null)
                        .WithMany("Services")
                        .HasForeignKey("TourProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourProductTranslation", b =>
                {
                    b.HasOne("TravelCore.Modules.Tour.Domain.TourProduct", null)
                        .WithMany("Translations")
                        .HasForeignKey("TourProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.ExperienceItinerary", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.ExperienceItineraryDay", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourExperienceSpecialization", b =>
                {
                    b.Navigation("Itinerary");
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourProduct", b =>
                {
                    b.Navigation("Destinations");

                    b.Navigation("MediaLinks");

                    b.Navigation("Policies");

                    b.Navigation("Requirements");

                    b.Navigation("Services");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
