// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCore.Modules.Tour.Infrastructure;

#nullable disable

namespace TravelCore.Modules.Tour.Infrastructure.Migrations
{
    [DbContext(typeof(TourDbContext))]
    [Migration("20260817024000_AddTourProductAgencyLink")]
    partial class AddTourProductAgencyLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tour")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<string>("ClassificationCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("classification_code");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("english_name");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<Guid?>("OriginDestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_destination_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_tour_products_agency_id");

                    b.HasIndex("ClassificationCode")
                        .HasDatabaseName("ix_tour_products_classification_code");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_tour_products_code");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_tour_products_created_at");

                    b.HasIndex("Kind")
                        .HasDatabaseName("ix_tour_products_kind");

                    b.HasIndex("OriginDestinationId")
                        .HasDatabaseName("ix_tour_products_origin_destination_id");

                    b.ToTable("tour_products", "tour");
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourProductDestination", b =>
                {
                    b.Property<Guid>("TourProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("tour_product_id");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_id");

                    b.HasKey("TourProductId", "DestinationId");

                    b.HasIndex("DestinationId")
                        .HasDatabaseName("ix_tour_product_destinations_destination_id");

                    b.ToTable("tour_product_destinations", "tour");
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourProductTranslation", b =>
                {
                    b.Property<Guid>("TourProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("tour_product_id");

                    b.Property<string>("LocaleCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale_code");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TourProductId", "LocaleCode");

                    b.HasIndex("LocaleCode")
                        .HasDatabaseName("ix_tour_product_translations_locale_code");

                    b.ToTable("tour_product_translations", "tour");
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourProductDestination", b =>
                {
                    b.HasOne("TravelCore.Modules.Tour.Domain.TourProduct", null)
                        .WithMany("Destinations")
                        .HasForeignKey("TourProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourProductTranslation", b =>
                {
                    b.HasOne("TravelCore.Modules.Tour.Domain.TourProduct", null)
                        .WithMany("Translations")
                        .HasForeignKey("TourProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Tour.Domain.TourProduct", b =>
                {
                    b.Navigation("Destinations");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
