// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCore.Modules.TripPlanner.Infrastructure;

#nullable disable

namespace TravelCore.Modules.TripPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(TripPlannerDbContext))]
    [Migration("20260818050000_AddLeadLifecycleBaseline")]
    partial class AddLeadLifecycleBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("trip_planner")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelCore.Modules.TripPlanner.Domain.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorReference")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_reference_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SourceTripIntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_trip_intent_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Instant>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.Property<Instant>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SourceTripIntentId")
                        .HasDatabaseName("ix_leads_source_trip_intent_id");

                    b.ToTable("leads", "trip_planner");
                });

            modelBuilder.Entity("TravelCore.Modules.TripPlanner.Domain.TripIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorReference")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_reference_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DraftAccessToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("draft_access_token");

                    b.Property<string>("PlanningNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("planning_note");

                    b.Property<int>("PlanningRevision")
                        .HasColumnType("integer")
                        .HasColumnName("planning_revision");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DraftAccessToken")
                        .IsUnique()
                        .HasDatabaseName("ux_trip_intents_draft_access_token");

                    b.ToTable("trip_intents", "trip_planner");
                });

            modelBuilder.Entity("TravelCore.Modules.TripPlanner.Domain.Lead", b =>
                {
                    b.HasOne("TravelCore.Modules.TripPlanner.Domain.TripIntent", null)
                        .WithMany()
                        .HasForeignKey("SourceTripIntentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("TravelCore.Modules.TripPlanner.Domain.LeadContactSnapshot", "Contact", b1 =>
                        {
                            b1.Property<Guid>("LeadId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DisplayName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("contact_display_name");

                            b1.Property<string>("Email")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("contact_email");

                            b1.Property<string>("NormalizedEmail")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("contact_normalized_email");

                            b1.Property<string>("Phone")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("contact_phone");

                            b1.HasKey("LeadId");

                            b1.ToTable("leads", "trip_planner");

                            b1.WithOwner()
                                .HasForeignKey("LeadId");
                        });

                    b.OwnsOne("TravelCore.Modules.TripPlanner.Domain.LeadSubmissionSnapshot", "Snapshot", b1 =>
                        {
                            b1.Property<Guid>("LeadId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CapturedPlanningNote")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("captured_planning_note");

                            b1.Property<int>("CapturedPlanningRevision")
                                .HasColumnType("integer")
                                .HasColumnName("captured_planning_revision");

                            b1.HasKey("LeadId");

                            b1.ToTable("leads", "trip_planner");

                            b1.WithOwner()
                                .HasForeignKey("LeadId");

                            b1.OwnsOne("TravelCore.Modules.TripPlanner.Domain.TravelPreferenceSnapshot", "Preferences", b2 =>
                                {
                                    b2.Property<Guid>("LeadSubmissionSnapshotLeadId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Accommodation")
                                        .HasMaxLength(32)
                                        .HasColumnType("character varying(32)")
                                        .HasColumnName("captured_preference_accommodation");

                                    b2.Property<string>("Transport")
                                        .HasMaxLength(32)
                                        .HasColumnType("character varying(32)")
                                        .HasColumnName("captured_preference_transport");

                                    b2.Property<string>("TravelerNote")
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("captured_preference_traveler_note");

                                    b2.Property<string>("TripStyle")
                                        .HasMaxLength(32)
                                        .HasColumnType("character varying(32)")
                                        .HasColumnName("captured_preference_trip_style");

                                    b2.HasKey("LeadSubmissionSnapshotLeadId");

                                    b2.ToTable("leads", "trip_planner");

                                    b2.WithOwner()
                                        .HasForeignKey("LeadSubmissionSnapshotLeadId");

                                    b2.OwnsMany("TravelCore.Modules.TripPlanner.Domain.DestinationPreference", "Destinations", b3 =>
                                        {
                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer");

                                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b3.Property<int>("Id"));

                                            b3.Property<bool>("IsUndecided")
                                                .HasColumnType("boolean")
                                                .HasColumnName("is_undecided");

                                            b3.Property<Guid?>("LogicalDestinationId")
                                                .HasColumnType("uuid")
                                                .HasColumnName("logical_destination_id");

                                            b3.Property<Guid>("OwnerId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("SortOrder")
                                                .HasColumnType("integer")
                                                .HasColumnName("sort_order");

                                            b3.HasKey("Id");

                                            b3.HasIndex("OwnerId");

                                            b3.ToTable("captured_preference_destination_preferences", "trip_planner");

                                            b3.WithOwner()
                                                .HasForeignKey("OwnerId");
                                        });

                                    b2.OwnsMany("TravelCore.Modules.TripPlanner.Domain.InterestPreference", "Interests", b3 =>
                                        {
                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer");

                                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b3.Property<int>("Id"));

                                            b3.Property<string>("Code")
                                                .IsRequired()
                                                .HasMaxLength(32)
                                                .HasColumnType("character varying(32)")
                                                .HasColumnName("interest_code");

                                            b3.Property<Guid>("OwnerId")
                                                .HasColumnType("uuid");

                                            b3.HasKey("Id");

                                            b3.HasIndex("OwnerId");

                                            b3.ToTable("captured_preference_interest_preferences", "trip_planner");

                                            b3.WithOwner()
                                                .HasForeignKey("OwnerId");
                                        });

                                    b2.OwnsOne("TravelCore.Modules.TripPlanner.Domain.BudgetPreference", "Budget", b3 =>
                                        {
                                            b3.Property<Guid>("TravelPreferenceSnapshotLeadSubmissionSnapshotLeadId")
                                                .HasColumnType("uuid");

                                            b3.Property<string>("CurrencyCode")
                                                .IsRequired()
                                                .HasMaxLength(12)
                                                .HasColumnType("character varying(12)")
                                                .HasColumnName("captured_preference_budget_currency_code");

                                            b3.Property<decimal?>("MaximumAmount")
                                                .HasColumnType("numeric(24,8)")
                                                .HasColumnName("captured_preference_budget_max_amount");

                                            b3.Property<decimal?>("MinimumAmount")
                                                .HasColumnType("numeric(24,8)")
                                                .HasColumnName("captured_preference_budget_min_amount");

                                            b3.HasKey("TravelPreferenceSnapshotLeadSubmissionSnapshotLeadId");

                                            b3.ToTable("leads", "trip_planner");

                                            b3.WithOwner()
                                                .HasForeignKey("TravelPreferenceSnapshotLeadSubmissionSnapshotLeadId");
                                        });

                                    b2.OwnsOne("TravelCore.Modules.TripPlanner.Domain.TravelTimingPreference", "Timing", b3 =>
                                        {
                                            b3.Property<Guid>("TravelPreferenceSnapshotLeadSubmissionSnapshotLeadId")
                                                .HasColumnType("uuid");

                                            b3.Property<int?>("ApproximateMonth")
                                                .HasColumnType("integer")
                                                .HasColumnName("captured_preference_approximate_month");

                                            b3.Property<string>("ApproximateSeason")
                                                .HasMaxLength(16)
                                                .HasColumnType("character varying(16)")
                                                .HasColumnName("captured_preference_approximate_season");

                                            b3.Property<int?>("ApproximateYear")
                                                .HasColumnType("integer")
                                                .HasColumnName("captured_preference_approximate_year");

                                            b3.Property<LocalDate?>("ExactEndDate")
                                                .HasColumnType("date")
                                                .HasColumnName("captured_preference_exact_end_date");

                                            b3.Property<LocalDate?>("ExactStartDate")
                                                .HasColumnType("date")
                                                .HasColumnName("captured_preference_exact_start_date");

                                            b3.Property<LocalDate?>("FlexibleEarliestStart")
                                                .HasColumnType("date")
                                                .HasColumnName("captured_preference_flexible_earliest_start");

                                            b3.Property<LocalDate?>("FlexibleLatestStart")
                                                .HasColumnType("date")
                                                .HasColumnName("captured_preference_flexible_latest_start");

                                            b3.Property<int?>("FlexibleMaxTripDurationDays")
                                                .HasColumnType("integer")
                                                .HasColumnName("captured_preference_flexible_max_trip_duration_days");

                                            b3.Property<string>("Kind")
                                                .IsRequired()
                                                .HasMaxLength(32)
                                                .HasColumnType("character varying(32)")
                                                .HasColumnName("captured_preference_timing_kind");

                                            b3.HasKey("TravelPreferenceSnapshotLeadSubmissionSnapshotLeadId");

                                            b3.ToTable("leads", "trip_planner");

                                            b3.WithOwner()
                                                .HasForeignKey("TravelPreferenceSnapshotLeadSubmissionSnapshotLeadId");
                                        });

                                    b2.OwnsOne("TravelCore.Modules.TripPlanner.Domain.PlannerTravelerComposition", "Travelers", b3 =>
                                        {
                                            b3.Property<Guid>("TravelPreferenceSnapshotLeadSubmissionSnapshotLeadId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("AdultCount")
                                                .HasColumnType("integer")
                                                .HasColumnName("captured_preference_adult_count");

                                            b3.Property<int>("ChildCount")
                                                .HasColumnType("integer")
                                                .HasColumnName("captured_preference_child_count");

                                            b3.Property<int>("InfantCount")
                                                .HasColumnType("integer")
                                                .HasColumnName("captured_preference_infant_count");

                                            b3.HasKey("TravelPreferenceSnapshotLeadSubmissionSnapshotLeadId");

                                            b3.ToTable("leads", "trip_planner");

                                            b3.WithOwner()
                                                .HasForeignKey("TravelPreferenceSnapshotLeadSubmissionSnapshotLeadId");
                                        });

                                    b2.Navigation("Budget");

                                    b2.Navigation("Destinations");

                                    b2.Navigation("Interests");

                                    b2.Navigation("Timing")
                                        .IsRequired();

                                    b2.Navigation("Travelers");
                                });

                            b1.Navigation("Preferences")
                                .IsRequired();
                        });

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("Snapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.TripPlanner.Domain.TripIntent", b =>
                {
                    b.OwnsOne("TravelCore.Modules.TripPlanner.Domain.TravelPreferences", "Preferences", b1 =>
                        {
                            b1.Property<Guid>("TripIntentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Accommodation")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("preference_accommodation");

                            b1.Property<string>("Transport")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("preference_transport");

                            b1.Property<string>("TravelerNote")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("preference_traveler_note");

                            b1.Property<string>("TripStyle")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("preference_trip_style");

                            b1.HasKey("TripIntentId");

                            b1.ToTable("trip_intents", "trip_planner");

                            b1.WithOwner()
                                .HasForeignKey("TripIntentId");

                            b1.OwnsMany("TravelCore.Modules.TripPlanner.Domain.DestinationPreference", "Destinations", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<bool>("IsUndecided")
                                        .HasColumnType("boolean")
                                        .HasColumnName("is_undecided");

                                    b2.Property<Guid?>("LogicalDestinationId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("logical_destination_id");

                                    b2.Property<Guid>("OwnerId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("SortOrder")
                                        .HasColumnType("integer")
                                        .HasColumnName("sort_order");

                                    b2.HasKey("Id");

                                    b2.HasIndex("OwnerId");

                                    b2.ToTable("preference_destination_preferences", "trip_planner");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnerId");
                                });

                            b1.OwnsMany("TravelCore.Modules.TripPlanner.Domain.InterestPreference", "Interests", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(32)
                                        .HasColumnType("character varying(32)")
                                        .HasColumnName("interest_code");

                                    b2.Property<Guid>("OwnerId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("OwnerId");

                                    b2.ToTable("preference_interest_preferences", "trip_planner");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnerId");
                                });

                            b1.OwnsOne("TravelCore.Modules.TripPlanner.Domain.BudgetPreference", "Budget", b2 =>
                                {
                                    b2.Property<Guid>("TravelPreferencesTripIntentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("CurrencyCode")
                                        .IsRequired()
                                        .HasMaxLength(12)
                                        .HasColumnType("character varying(12)")
                                        .HasColumnName("preference_budget_currency_code");

                                    b2.Property<decimal?>("MaximumAmount")
                                        .HasColumnType("numeric(24,8)")
                                        .HasColumnName("preference_budget_max_amount");

                                    b2.Property<decimal?>("MinimumAmount")
                                        .HasColumnType("numeric(24,8)")
                                        .HasColumnName("preference_budget_min_amount");

                                    b2.HasKey("TravelPreferencesTripIntentId");

                                    b2.ToTable("trip_intents", "trip_planner");

                                    b2.WithOwner()
                                        .HasForeignKey("TravelPreferencesTripIntentId");
                                });

                            b1.OwnsOne("TravelCore.Modules.TripPlanner.Domain.TravelTimingPreference", "Timing", b2 =>
                                {
                                    b2.Property<Guid>("TravelPreferencesTripIntentId")
                                        .HasColumnType("uuid");

                                    b2.Property<int?>("ApproximateMonth")
                                        .HasColumnType("integer")
                                        .HasColumnName("preference_approximate_month");

                                    b2.Property<string>("ApproximateSeason")
                                        .HasMaxLength(16)
                                        .HasColumnType("character varying(16)")
                                        .HasColumnName("preference_approximate_season");

                                    b2.Property<int?>("ApproximateYear")
                                        .HasColumnType("integer")
                                        .HasColumnName("preference_approximate_year");

                                    b2.Property<LocalDate?>("ExactEndDate")
                                        .HasColumnType("date")
                                        .HasColumnName("preference_exact_end_date");

                                    b2.Property<LocalDate?>("ExactStartDate")
                                        .HasColumnType("date")
                                        .HasColumnName("preference_exact_start_date");

                                    b2.Property<LocalDate?>("FlexibleEarliestStart")
                                        .HasColumnType("date")
                                        .HasColumnName("preference_flexible_earliest_start");

                                    b2.Property<LocalDate?>("FlexibleLatestStart")
                                        .HasColumnType("date")
                                        .HasColumnName("preference_flexible_latest_start");

                                    b2.Property<int?>("FlexibleMaxTripDurationDays")
                                        .HasColumnType("integer")
                                        .HasColumnName("preference_flexible_max_trip_duration_days");

                                    b2.Property<string>("Kind")
                                        .IsRequired()
                                        .HasMaxLength(32)
                                        .HasColumnType("character varying(32)")
                                        .HasColumnName("preference_timing_kind");

                                    b2.HasKey("TravelPreferencesTripIntentId");

                                    b2.ToTable("trip_intents", "trip_planner");

                                    b2.WithOwner()
                                        .HasForeignKey("TravelPreferencesTripIntentId");
                                });

                            b1.OwnsOne("TravelCore.Modules.TripPlanner.Domain.PlannerTravelerComposition", "Travelers", b2 =>
                                {
                                    b2.Property<Guid>("TravelPreferencesTripIntentId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("AdultCount")
                                        .HasColumnType("integer")
                                        .HasColumnName("preference_adult_count");

                                    b2.Property<int>("ChildCount")
                                        .HasColumnType("integer")
                                        .HasColumnName("preference_child_count");

                                    b2.Property<int>("InfantCount")
                                        .HasColumnType("integer")
                                        .HasColumnName("preference_infant_count");

                                    b2.HasKey("TravelPreferencesTripIntentId");

                                    b2.ToTable("trip_intents", "trip_planner");

                                    b2.WithOwner()
                                        .HasForeignKey("TravelPreferencesTripIntentId");
                                });

                            b1.Navigation("Budget");

                            b1.Navigation("Destinations");

                            b1.Navigation("Interests");

                            b1.Navigation("Timing")
                                .IsRequired();

                            b1.Navigation("Travelers");
                        });

                    b.Navigation("Preferences")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
