// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCore.Modules.TripPlanner.Infrastructure;

#nullable disable

namespace TravelCore.Modules.TripPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(TripPlannerDbContext))]
    [Migration("20260818020000_AddTripIntentLeadBaseline")]
    partial class AddTripIntentLeadBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("trip_planner")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelCore.Modules.TripPlanner.Domain.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SourceTripIntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_trip_intent_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Instant>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id");

                    b.HasIndex("SourceTripIntentId")
                        .HasDatabaseName("ix_leads_source_trip_intent_id");

                    b.ToTable("leads", "trip_planner");
                });

            modelBuilder.Entity("TravelCore.Modules.TripPlanner.Domain.TripIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PlanningNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("planning_note");

                    b.Property<int>("PlanningRevision")
                        .HasColumnType("integer")
                        .HasColumnName("planning_revision");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("trip_intents", "trip_planner");
                });

            modelBuilder.Entity("TravelCore.Modules.TripPlanner.Domain.Lead", b =>
                {
                    b.HasOne("TravelCore.Modules.TripPlanner.Domain.TripIntent", null)
                        .WithMany()
                        .HasForeignKey("SourceTripIntentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("TravelCore.Modules.TripPlanner.Domain.LeadSubmissionSnapshot", "Snapshot", b1 =>
                        {
                            b1.Property<Guid>("LeadId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CapturedPlanningNote")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("captured_planning_note");

                            b1.Property<int>("CapturedPlanningRevision")
                                .HasColumnType("integer")
                                .HasColumnName("captured_planning_revision");

                            b1.HasKey("LeadId");

                            b1.ToTable("leads", "trip_planner");

                            b1.WithOwner()
                                .HasForeignKey("LeadId");
                        });

                    b.Navigation("Snapshot")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
