// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCore.Modules.Flight.Infrastructure;

#nullable disable

namespace TravelCore.Modules.Flight.Infrastructure.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    [Migration("20260818220400_AddFlightPaymentAndTicketing")]
    partial class AddFlightPaymentAndTicketing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("flight")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightBaggageAllowanceSnapshot", b =>
                {
                    b.Property<Guid>("FlightOfferSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_offer_snapshot_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Category")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<short?>("PassengerCategory")
                        .HasColumnType("smallint")
                        .HasColumnName("passenger_category");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Unit")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("unit");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric(24,8)")
                        .HasColumnName("weight");

                    b.HasKey("FlightOfferSnapshotId", "Ordinal");

                    b.ToTable("flight_baggage_allowance_snapshots", "flight");
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Instant?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status");

                    b.Property<short>("TripType")
                        .HasColumnType("smallint")
                        .HasColumnName("trip_type");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("flight_bookings", "flight", t =>
                        {
                            t.HasCheckConstraint("ck_flight_bookings_status", "status IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_flight_bookings_trip_type", "trip_type IN (1, 2)");

                            t.HasCheckConstraint("ck_flight_bookings_version_nonnegative", "version >= 0");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightBookingMonetarySnapshot", b =>
                {
                    b.Property<Guid>("FlightOfferSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_offer_snapshot_id");

                    b.Property<Guid>("FlightBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_booking_id");

                    b.HasKey("FlightOfferSnapshotId");

                    b.HasIndex("FlightBookingId")
                        .IsUnique()
                        .HasDatabaseName("ux_flight_booking_monetary_snapshots_flight_booking_id");

                    b.ToTable("flight_booking_monetary_snapshots", "flight");
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightBookingPaymentCompensationEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<Guid>("FlightBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_booking_id");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<short>("Reason")
                        .HasColumnType("smallint")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("FlightBookingId")
                        .IsUnique()
                        .HasDatabaseName("ux_flight_booking_payment_compensation_evidence_flight_booking_id");

                    b.ToTable("flight_booking_payment_compensation_evidence", "flight", t =>
                        {
                            t.HasCheckConstraint("ck_flight_booking_payment_compensation_reason", "reason IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightBookingPaymentEvidence", b =>
                {
                    b.Property<Guid>("FlightBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_booking_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<Instant>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("FlightBookingId");

                    b.HasIndex("PaymentId")
                        .IsUnique()
                        .HasDatabaseName("ux_flight_booking_payment_evidence_payment_id");

                    b.ToTable("flight_booking_payment_evidence", "flight");
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightFareRulesSnapshot", b =>
                {
                    b.Property<Guid>("FlightOfferSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_offer_snapshot_id");

                    b.Property<bool>("Changeable")
                        .HasColumnType("boolean")
                        .HasColumnName("changeable");

                    b.Property<bool>("PartialRefundRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("partial_refund_required");

                    b.Property<bool>("Refundable")
                        .HasColumnType("boolean")
                        .HasColumnName("refundable");

                    b.Property<Instant?>("TicketingDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ticketing_deadline");

                    b.HasKey("FlightOfferSnapshotId");

                    b.ToTable("flight_fare_rule_snapshots", "flight");
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightJourney", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FlightBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_booking_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.HasKey("Id");

                    b.HasIndex("FlightBookingId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_flight_journeys_booking_ordinal");

                    b.ToTable("flight_journeys", "flight");
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightOfferIdempotencyRecord", b =>
                {
                    b.Property<Guid>("FlightBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_booking_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_offer_snapshot_id");

                    b.HasKey("FlightBookingId", "IdempotencyKey");

                    b.ToTable("flight_offer_idempotency", "flight");
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightOfferSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<string>("BookingClass")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("booking_class");

                    b.Property<string>("Cabin")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cabin");

                    b.Property<string>("FareBasis")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("fare_basis");

                    b.Property<string>("FareFamily")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fare_family");

                    b.Property<Guid>("FlightBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_booking_id");

                    b.Property<Instant>("OfferExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("offer_expires_at");

                    b.Property<Instant>("QuotedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quoted_at");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_key");

                    b.Property<string>("SourceOfferReference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_offer_reference");

                    b.Property<short>("TripType")
                        .HasColumnType("smallint")
                        .HasColumnName("trip_type");

                    b.HasKey("Id");

                    b.HasIndex("FlightBookingId")
                        .IsUnique()
                        .HasDatabaseName("ux_flight_offer_snapshots_flight_booking_id");

                    b.HasIndex("SourceKey", "SourceOfferReference")
                        .IsUnique()
                        .HasDatabaseName("ux_flight_offer_snapshots_source_offer");

                    b.ToTable("flight_offer_snapshots", "flight");
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightPassenger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Category")
                        .HasColumnType("smallint")
                        .HasColumnName("category");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("family_name");

                    b.Property<Guid>("FlightBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_booking_id");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("given_name");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.HasKey("Id");

                    b.HasIndex("FlightBookingId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_flight_passengers_booking_ordinal");

                    b.ToTable("flight_passengers", "flight", t =>
                        {
                            t.HasCheckConstraint("ck_flight_passengers_category", "category IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightPassengerCategoryFareSnapshot", b =>
                {
                    b.Property<Guid>("FlightOfferSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_offer_snapshot_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<short>("Category")
                        .HasColumnType("smallint")
                        .HasColumnName("category");

                    b.Property<int>("PassengerCount")
                        .HasColumnType("integer")
                        .HasColumnName("passenger_count");

                    b.HasKey("FlightOfferSnapshotId", "Ordinal");

                    b.ToTable("flight_passenger_category_fare_snapshots", "flight", t =>
                        {
                            t.HasCheckConstraint("ck_flight_passenger_category_fare_snapshots_category", "category IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightReconciliationIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_supplier_reservation_attempt_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("detail");

                    b.Property<Guid>("FlightBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_booking_id");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_supplier_reservation_id");

                    b.HasKey("Id");

                    b.HasIndex("FlightBookingId")
                        .HasDatabaseName("ix_flight_reconciliation_issues_flight_booking_id");

                    b.ToTable("flight_reconciliation_issues", "flight", t =>
                        {
                            t.HasCheckConstraint("ck_flight_reconciliation_issues_kind", "kind IN (1, 2, 3, 4, 5, 6, 7, 8, 9)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("ArrivalAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrival_at");

                    b.Property<string>("ArrivalTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("arrival_time_zone_id");

                    b.Property<Instant>("DepartureAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_at");

                    b.Property<string>("DepartureTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("departure_time_zone_id");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("destination_airport_iata");

                    b.Property<Guid>("FlightBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_booking_id");

                    b.Property<Guid>("FlightJourneyId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_journey_id");

                    b.Property<string>("FlightNumber")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("flight_number");

                    b.Property<string>("MarketingCarrier")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("marketing_carrier_iata");

                    b.Property<string>("OperatingCarrier")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("operating_carrier_iata");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("origin_airport_iata");

                    b.HasKey("Id");

                    b.HasIndex("FlightJourneyId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_flight_segments_journey_ordinal");

                    b.ToTable("flight_segments", "flight", t =>
                        {
                            t.HasCheckConstraint("ck_flight_segments_arrival_after_departure", "arrival_at > departure_at");

                            t.HasCheckConstraint("ck_flight_segments_origin_destination_differ", "origin_airport_iata <> destination_airport_iata");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightSupplierReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Instant?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<Guid>("FlightBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_booking_id");

                    b.Property<Instant?>("ReservationExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reservation_expires_at");

                    b.Property<string>("ReservationLocator")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reservation_locator");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_key");

                    b.Property<string>("SourceReservationReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_reservation_reference");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("FlightBookingId")
                        .IsUnique()
                        .HasDatabaseName("ux_flight_supplier_reservations_flight_booking_id");

                    b.HasIndex("SourceKey", "SourceReservationReference")
                        .IsUnique()
                        .HasDatabaseName("ux_flight_supplier_reservations_source_ref")
                        .HasFilter("source_reservation_reference IS NOT NULL");

                    b.ToTable("flight_supplier_reservations", "flight", t =>
                        {
                            t.HasCheckConstraint("ck_flight_supplier_reservations_status", "status IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightSupplierReservationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<Instant?>("InitiatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("initiated_at");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_supplier_reservation_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId")
                        .IsUnique()
                        .HasDatabaseName("ux_flight_supplier_reservation_attempts_one_unresolved")
                        .HasFilter("status IN (1, 2)");

                    b.ToTable("flight_supplier_reservation_attempts", "flight", t =>
                        {
                            t.HasCheckConstraint("ck_flight_supplier_reservation_attempts_status", "status IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightSupplierReservationIdempotencyRecord", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_supplier_reservation_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_supplier_reservation_attempt_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("ReservationId", "IdempotencyKey");

                    b.ToTable("flight_supplier_reservation_idempotency", "flight");
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FlightBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_booking_id");

                    b.Property<Instant?>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_passenger_id");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_key");

                    b.Property<string>("SourceTicketNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_ticket_number");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SourceTicketNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_flight_tickets_source_ticket_number")
                        .HasFilter("source_ticket_number IS NOT NULL");

                    b.HasIndex("FlightBookingId", "PassengerId")
                        .IsUnique()
                        .HasDatabaseName("ux_flight_tickets_booking_passenger");

                    b.ToTable("flight_tickets", "flight", t =>
                        {
                            t.HasCheckConstraint("ck_flight_tickets_status", "status IN (1, 2)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightTicketingAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<Guid>("FlightBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_booking_id");

                    b.Property<Instant?>("InitiatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("initiated_at");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Instant?>("SucceededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("succeeded_at");

                    b.HasKey("Id");

                    b.HasIndex("FlightBookingId")
                        .IsUnique()
                        .HasDatabaseName("ux_flight_ticketing_attempts_one_unresolved")
                        .HasFilter("status IN (1, 2)");

                    b.ToTable("flight_ticketing_attempts", "flight", t =>
                        {
                            t.HasCheckConstraint("ck_flight_ticketing_attempts_status", "status IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightTicketingIdempotencyRecord", b =>
                {
                    b.Property<Guid>("FlightBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_booking_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_ticketing_attempt_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("FlightBookingId", "IdempotencyKey");

                    b.ToTable("flight_ticketing_idempotency", "flight");
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Infrastructure.FlightOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("message_type");

                    b.Property<Instant>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Instant?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_flight_outbox_messages_processed_at");

                    b.ToTable("outbox_messages", "flight");
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Infrastructure.FlightPaymentSuccessInboxRecord", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<Instant>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("PaymentId");

                    b.ToTable("flight_payment_success_inbox", "flight");
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Infrastructure.FlightRefundSuccessInboxRecord", b =>
                {
                    b.Property<Guid>("RefundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("refund_id");

                    b.Property<Instant>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("RefundId");

                    b.ToTable("flight_refund_success_inbox", "flight");
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightBaggageAllowanceSnapshot", b =>
                {
                    b.HasOne("TravelCore.Modules.Flight.Domain.FlightFareRulesSnapshot", null)
                        .WithMany("Baggage")
                        .HasForeignKey("FlightOfferSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightBookingMonetarySnapshot", b =>
                {
                    b.HasOne("TravelCore.Modules.Flight.Domain.FlightOfferSnapshot", null)
                        .WithOne("Monetary")
                        .HasForeignKey("TravelCore.Modules.Flight.Domain.FlightBookingMonetarySnapshot", "FlightOfferSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TravelCore.Money.Money", "BaseFare", b1 =>
                        {
                            b1.Property<Guid>("FlightBookingMonetarySnapshotFlightOfferSnapshotId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(24,8)")
                                .HasColumnName("base_fare_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("base_fare_currency_code");

                            b1.HasKey("FlightBookingMonetarySnapshotFlightOfferSnapshotId");

                            b1.ToTable("flight_booking_monetary_snapshots", "flight");

                            b1.WithOwner()
                                .HasForeignKey("FlightBookingMonetarySnapshotFlightOfferSnapshotId");
                        });

                    b.OwnsOne("TravelCore.Money.Money", "Fees", b1 =>
                        {
                            b1.Property<Guid>("FlightBookingMonetarySnapshotFlightOfferSnapshotId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(24,8)")
                                .HasColumnName("fees_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("fees_currency_code");

                            b1.HasKey("FlightBookingMonetarySnapshotFlightOfferSnapshotId");

                            b1.ToTable("flight_booking_monetary_snapshots", "flight");

                            b1.WithOwner()
                                .HasForeignKey("FlightBookingMonetarySnapshotFlightOfferSnapshotId");
                        });

                    b.OwnsOne("TravelCore.Money.Money", "Taxes", b1 =>
                        {
                            b1.Property<Guid>("FlightBookingMonetarySnapshotFlightOfferSnapshotId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(24,8)")
                                .HasColumnName("taxes_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("taxes_currency_code");

                            b1.HasKey("FlightBookingMonetarySnapshotFlightOfferSnapshotId");

                            b1.ToTable("flight_booking_monetary_snapshots", "flight");

                            b1.WithOwner()
                                .HasForeignKey("FlightBookingMonetarySnapshotFlightOfferSnapshotId");
                        });

                    b.OwnsOne("TravelCore.Money.Money", "Total", b1 =>
                        {
                            b1.Property<Guid>("FlightBookingMonetarySnapshotFlightOfferSnapshotId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(24,8)")
                                .HasColumnName("total_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("currency_code");

                            b1.HasKey("FlightBookingMonetarySnapshotFlightOfferSnapshotId");

                            b1.ToTable("flight_booking_monetary_snapshots", "flight");

                            b1.WithOwner()
                                .HasForeignKey("FlightBookingMonetarySnapshotFlightOfferSnapshotId");
                        });

                    b.Navigation("BaseFare")
                        .IsRequired();

                    b.Navigation("Fees")
                        .IsRequired();

                    b.Navigation("Taxes")
                        .IsRequired();

                    b.Navigation("Total")
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightBookingPaymentCompensationEvidence", b =>
                {
                    b.HasOne("TravelCore.Modules.Flight.Domain.FlightBooking", null)
                        .WithMany()
                        .HasForeignKey("FlightBookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightBookingPaymentEvidence", b =>
                {
                    b.HasOne("TravelCore.Modules.Flight.Domain.FlightBooking", null)
                        .WithMany()
                        .HasForeignKey("FlightBookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightFareRulesSnapshot", b =>
                {
                    b.HasOne("TravelCore.Modules.Flight.Domain.FlightOfferSnapshot", null)
                        .WithOne("FareRules")
                        .HasForeignKey("TravelCore.Modules.Flight.Domain.FlightFareRulesSnapshot", "FlightOfferSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TravelCore.Money.Money", "CancelPenalty", b1 =>
                        {
                            b1.Property<Guid>("FlightFareRulesSnapshotFlightOfferSnapshotId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(24,8)")
                                .HasColumnName("cancel_penalty_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("cancel_penalty_currency_code");

                            b1.HasKey("FlightFareRulesSnapshotFlightOfferSnapshotId");

                            b1.ToTable("flight_fare_rule_snapshots", "flight");

                            b1.WithOwner()
                                .HasForeignKey("FlightFareRulesSnapshotFlightOfferSnapshotId");
                        });

                    b.OwnsOne("TravelCore.Money.Money", "ChangePenalty", b1 =>
                        {
                            b1.Property<Guid>("FlightFareRulesSnapshotFlightOfferSnapshotId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(24,8)")
                                .HasColumnName("change_penalty_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("change_penalty_currency_code");

                            b1.HasKey("FlightFareRulesSnapshotFlightOfferSnapshotId");

                            b1.ToTable("flight_fare_rule_snapshots", "flight");

                            b1.WithOwner()
                                .HasForeignKey("FlightFareRulesSnapshotFlightOfferSnapshotId");
                        });

                    b.Navigation("CancelPenalty");

                    b.Navigation("ChangePenalty");
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightJourney", b =>
                {
                    b.HasOne("TravelCore.Modules.Flight.Domain.FlightBooking", null)
                        .WithMany("Journeys")
                        .HasForeignKey("FlightBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightOfferIdempotencyRecord", b =>
                {
                    b.HasOne("TravelCore.Modules.Flight.Domain.FlightBooking", null)
                        .WithMany()
                        .HasForeignKey("FlightBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightOfferSnapshot", b =>
                {
                    b.HasOne("TravelCore.Modules.Flight.Domain.FlightBooking", null)
                        .WithMany()
                        .HasForeignKey("FlightBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightPassenger", b =>
                {
                    b.HasOne("TravelCore.Modules.Flight.Domain.FlightBooking", null)
                        .WithMany("Passengers")
                        .HasForeignKey("FlightBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightPassengerCategoryFareSnapshot", b =>
                {
                    b.HasOne("TravelCore.Modules.Flight.Domain.FlightBookingMonetarySnapshot", null)
                        .WithMany("CategoryFares")
                        .HasForeignKey("FlightOfferSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TravelCore.Money.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("FlightPassengerCategoryFareSnapshotFlightOfferSnapshotId")
                                .HasColumnType("uuid");

                            b1.Property<int>("FlightPassengerCategoryFareSnapshotOrdinal")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(24,8)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("currency_code");

                            b1.HasKey("FlightPassengerCategoryFareSnapshotFlightOfferSnapshotId", "FlightPassengerCategoryFareSnapshotOrdinal");

                            b1.ToTable("flight_passenger_category_fare_snapshots", "flight");

                            b1.WithOwner()
                                .HasForeignKey("FlightPassengerCategoryFareSnapshotFlightOfferSnapshotId", "FlightPassengerCategoryFareSnapshotOrdinal");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightReconciliationIssue", b =>
                {
                    b.HasOne("TravelCore.Modules.Flight.Domain.FlightBooking", null)
                        .WithMany()
                        .HasForeignKey("FlightBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightSegment", b =>
                {
                    b.HasOne("TravelCore.Modules.Flight.Domain.FlightJourney", null)
                        .WithMany("Segments")
                        .HasForeignKey("FlightJourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightSupplierReservation", b =>
                {
                    b.HasOne("TravelCore.Modules.Flight.Domain.FlightBooking", null)
                        .WithMany()
                        .HasForeignKey("FlightBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightSupplierReservationAttempt", b =>
                {
                    b.HasOne("TravelCore.Modules.Flight.Domain.FlightSupplierReservation", null)
                        .WithMany("Attempts")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightSupplierReservationIdempotencyRecord", b =>
                {
                    b.HasOne("TravelCore.Modules.Flight.Domain.FlightSupplierReservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightTicket", b =>
                {
                    b.HasOne("TravelCore.Modules.Flight.Domain.FlightBooking", null)
                        .WithMany()
                        .HasForeignKey("FlightBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightTicketingAttempt", b =>
                {
                    b.HasOne("TravelCore.Modules.Flight.Domain.FlightBooking", null)
                        .WithMany()
                        .HasForeignKey("FlightBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightTicketingIdempotencyRecord", b =>
                {
                    b.HasOne("TravelCore.Modules.Flight.Domain.FlightBooking", null)
                        .WithMany()
                        .HasForeignKey("FlightBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightBooking", b =>
                {
                    b.Navigation("Journeys");

                    b.Navigation("Passengers");
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightBookingMonetarySnapshot", b =>
                {
                    b.Navigation("CategoryFares");
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightFareRulesSnapshot", b =>
                {
                    b.Navigation("Baggage");
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightJourney", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightOfferSnapshot", b =>
                {
                    b.Navigation("FareRules")
                        .IsRequired();

                    b.Navigation("Monetary")
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightSupplierReservation", b =>
                {
                    b.Navigation("Attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
