// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCore.Modules.Flight.Infrastructure;

#nullable disable

namespace TravelCore.Modules.Flight.Infrastructure.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    [Migration("20260818220100_AddFlightBookingItinerary")]
    partial class AddFlightBookingItinerary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("flight")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("TripType")
                        .HasColumnType("smallint")
                        .HasColumnName("trip_type");

                    b.HasKey("Id");

                    b.ToTable("flight_bookings", "flight", t =>
                        {
                            t.HasCheckConstraint("ck_flight_bookings_trip_type", "trip_type IN (1, 2)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightJourney", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FlightBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_booking_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.HasKey("Id");

                    b.HasIndex("FlightBookingId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_flight_journeys_booking_ordinal");

                    b.ToTable("flight_journeys", "flight");
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightPassenger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Category")
                        .HasColumnType("smallint")
                        .HasColumnName("category");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("family_name");

                    b.Property<Guid>("FlightBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_booking_id");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("given_name");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.HasKey("Id");

                    b.HasIndex("FlightBookingId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_flight_passengers_booking_ordinal");

                    b.ToTable("flight_passengers", "flight", t =>
                        {
                            t.HasCheckConstraint("ck_flight_passengers_category", "category IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("ArrivalAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrival_at");

                    b.Property<string>("ArrivalTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("arrival_time_zone_id");

                    b.Property<Instant>("DepartureAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_at");

                    b.Property<string>("DepartureTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("departure_time_zone_id");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("destination_airport_iata");

                    b.Property<Guid>("FlightBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_booking_id");

                    b.Property<Guid>("FlightJourneyId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_journey_id");

                    b.Property<string>("FlightNumber")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("flight_number");

                    b.Property<string>("MarketingCarrier")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("marketing_carrier_iata");

                    b.Property<string>("OperatingCarrier")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("operating_carrier_iata");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("origin_airport_iata");

                    b.HasKey("Id");

                    b.HasIndex("FlightJourneyId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_flight_segments_journey_ordinal");

                    b.ToTable("flight_segments", "flight", t =>
                        {
                            t.HasCheckConstraint("ck_flight_segments_arrival_after_departure", "arrival_at > departure_at");

                            t.HasCheckConstraint("ck_flight_segments_origin_destination_differ", "origin_airport_iata <> destination_airport_iata");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightJourney", b =>
                {
                    b.HasOne("TravelCore.Modules.Flight.Domain.FlightBooking", null)
                        .WithMany("Journeys")
                        .HasForeignKey("FlightBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightPassenger", b =>
                {
                    b.HasOne("TravelCore.Modules.Flight.Domain.FlightBooking", null)
                        .WithMany("Passengers")
                        .HasForeignKey("FlightBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightSegment", b =>
                {
                    b.HasOne("TravelCore.Modules.Flight.Domain.FlightJourney", null)
                        .WithMany("Segments")
                        .HasForeignKey("FlightJourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightBooking", b =>
                {
                    b.Navigation("Journeys");

                    b.Navigation("Passengers");
                });

            modelBuilder.Entity("TravelCore.Modules.Flight.Domain.FlightJourney", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
