// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCore.Modules.Pricing.Infrastructure;

#nullable disable

namespace TravelCore.Modules.Pricing.Infrastructure.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    [Migration("20260817120000_AddQuoteRequestedDisplayCurrency")]
    partial class AddQuoteRequestedDisplayCurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pricing")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelCore.Modules.Pricing.Domain.Price", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("ix_prices_target_type_target_id");

                    b.ToTable("prices", "pricing");
                });

            modelBuilder.Entity("TravelCore.Modules.Pricing.Domain.PriceComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<Guid>("PriceId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("PriceId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_price_components_price_code")
                        .HasFilter("code IS NOT NULL");

                    b.HasIndex("PriceId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_price_components_price_sort_order");

                    b.ToTable("price_components", "pricing");
                });

            modelBuilder.Entity("TravelCore.Modules.Pricing.Domain.PriceOccupancyRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("MarketPriceType")
                        .HasColumnType("smallint")
                        .HasColumnName("market_price_type");

                    b.Property<short>("OccupancyCategory")
                        .HasColumnType("smallint")
                        .HasColumnName("occupancy_category");

                    b.Property<short>("PassengerCategory")
                        .HasColumnType("smallint")
                        .HasColumnName("passenger_category");

                    b.Property<Guid>("PriceId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("PriceId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_price_occupancy_rules_price_sort_order");

                    b.HasIndex("PriceId", "MarketPriceType", "PassengerCategory", "OccupancyCategory")
                        .IsUnique()
                        .HasDatabaseName("ux_price_occupancy_rules_price_market_passenger_occupancy");

                    b.ToTable("price_occupancy_rules", "pricing");
                });

            modelBuilder.Entity("TravelCore.Modules.Pricing.Domain.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RequestedDisplayCurrency")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("requested_display_currency");

                    b.Property<Guid?>("SnapshotTargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_target_id");

                    b.Property<string>("SnapshotTargetType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("snapshot_target_type");

                    b.Property<Guid>("SourcePriceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_price_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_quotes_expires_at");

                    b.HasIndex("SourcePriceId")
                        .HasDatabaseName("ix_quotes_source_price_id");

                    b.ToTable("quotes", "pricing");
                });

            modelBuilder.Entity("TravelCore.Modules.Pricing.Domain.QuoteSnapshotComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_quote_snapshot_components_quote_code")
                        .HasFilter("code IS NOT NULL");

                    b.HasIndex("QuoteId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_quote_snapshot_components_quote_sort_order");

                    b.ToTable("quote_snapshot_components", "pricing");
                });

            modelBuilder.Entity("TravelCore.Modules.Pricing.Domain.PriceComponent", b =>
                {
                    b.HasOne("TravelCore.Modules.Pricing.Domain.Price", null)
                        .WithMany("Components")
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TravelCore.Money.Money", "Money", b1 =>
                        {
                            b1.Property<Guid>("PriceComponentId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(24,8)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("currency_code");

                            b1.HasKey("PriceComponentId");

                            b1.ToTable("price_components", "pricing");

                            b1.WithOwner()
                                .HasForeignKey("PriceComponentId");
                        });

                    b.Navigation("Money")
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Pricing.Domain.PriceOccupancyRule", b =>
                {
                    b.HasOne("TravelCore.Modules.Pricing.Domain.Price", null)
                        .WithMany("OccupancyRules")
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TravelCore.Money.Money", "Money", b1 =>
                        {
                            b1.Property<Guid>("PriceOccupancyRuleId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(24,8)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("currency_code");

                            b1.HasKey("PriceOccupancyRuleId");

                            b1.ToTable("price_occupancy_rules", "pricing");

                            b1.WithOwner()
                                .HasForeignKey("PriceOccupancyRuleId");
                        });

                    b.Navigation("Money")
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Pricing.Domain.QuoteSnapshotComponent", b =>
                {
                    b.HasOne("TravelCore.Modules.Pricing.Domain.Quote", null)
                        .WithMany("SnapshotComponents")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TravelCore.Money.Money", "Money", b1 =>
                        {
                            b1.Property<Guid>("QuoteSnapshotComponentId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(24,8)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("currency_code");

                            b1.HasKey("QuoteSnapshotComponentId");

                            b1.ToTable("quote_snapshot_components", "pricing");

                            b1.WithOwner()
                                .HasForeignKey("QuoteSnapshotComponentId");
                        });

                    b.Navigation("Money")
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Pricing.Domain.Price", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("OccupancyRules");
                });

            modelBuilder.Entity("TravelCore.Modules.Pricing.Domain.Quote", b =>
                {
                    b.Navigation("SnapshotComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
