// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCore.Modules.Ugc.Infrastructure;

#nullable disable

namespace TravelCore.Modules.Ugc.Infrastructure.Migrations
{
    [DbContext(typeof(UgcDbContext))]
    [Migration("20260817220000_AddReviewRatingBaseline")]
    partial class AddReviewRatingBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ugc")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelCore.Modules.Ugc.Domain.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("Body")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("body");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("OverallRating")
                        .HasColumnType("smallint")
                        .HasColumnName("overall_rating");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_reviews_actor_id");

                    b.ToTable("reviews", "ugc");
                });

            modelBuilder.Entity("TravelCore.Modules.Ugc.Domain.ReviewDimensionRating", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.Property<string>("DimensionCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("dimension_code");

                    b.Property<short>("Value")
                        .HasColumnType("smallint")
                        .HasColumnName("value");

                    b.HasKey("ReviewId", "DimensionCode");

                    b.ToTable("review_dimension_ratings", "ugc");
                });

            modelBuilder.Entity("TravelCore.Modules.Ugc.Domain.ReviewDimensionRating", b =>
                {
                    b.HasOne("TravelCore.Modules.Ugc.Domain.Review", null)
                        .WithMany("DimensionRatings")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Ugc.Domain.Review", b =>
                {
                    b.Navigation("DimensionRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
