// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCore.Modules.Booking.Infrastructure;

#nullable disable

namespace TravelCore.Modules.Booking.Infrastructure.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20260818012053_AddCapacityHoldAndDepartureAccount")]
    partial class AddCapacityHoldAndDepartureAccount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("booking")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Instant>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.Property<Guid>("TourDeparture")
                        .HasColumnType("uuid")
                        .HasColumnName("tour_departure_id");

                    b.HasKey("Id");

                    b.HasIndex("TourDeparture")
                        .HasDatabaseName("ix_bookings_tour_departure_id");

                    b.ToTable("bookings", "booking");
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.CapacityHold", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<int>("ObservedConfiguredCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("observed_configured_capacity");

                    b.Property<int>("SeatCount")
                        .HasColumnType("integer")
                        .HasColumnName("seat_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Instant>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.Property<Guid>("TourDeparture")
                        .HasColumnType("uuid")
                        .HasColumnName("tour_departure_id");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ux_capacity_holds_one_active_per_booking")
                        .HasFilter("status = 1");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_capacity_holds_idempotency_key");

                    b.HasIndex("TourDeparture")
                        .HasDatabaseName("ix_capacity_holds_tour_departure_id");

                    b.ToTable("capacity_holds", "booking", t =>
                        {
                            t.HasCheckConstraint("ck_capacity_holds_expires_after_created", "expires_at > created_at");

                            t.HasCheckConstraint("ck_capacity_holds_observed_capacity_positive", "observed_configured_capacity > 0");

                            t.HasCheckConstraint("ck_capacity_holds_seat_count_positive", "seat_count > 0");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.DepartureCapacityAccount", b =>
                {
                    b.Property<Guid>("TourDeparture")
                        .HasColumnType("uuid")
                        .HasColumnName("tour_departure_id");

                    b.Property<int>("ActiveSeats")
                        .HasColumnType("integer")
                        .HasColumnName("active_seats");

                    b.Property<int>("ConsumedSeats")
                        .HasColumnType("integer")
                        .HasColumnName("consumed_seats");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("TourDeparture");

                    b.ToTable("departure_capacity_accounts", "booking", t =>
                        {
                            t.HasCheckConstraint("ck_departure_capacity_accounts_active_seats_nonnegative", "active_seats >= 0");

                            t.HasCheckConstraint("ck_departure_capacity_accounts_consumed_seats_nonnegative", "consumed_seats >= 0");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.CapacityHold", b =>
                {
                    b.HasOne("TravelCore.Modules.Booking.Domain.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
