// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCore.Modules.Booking.Infrastructure;

#nullable disable

namespace TravelCore.Modules.Booking.Infrastructure.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20260818100819_AddBookingCompensationOutboxAndRefundInbox")]
    partial class AddBookingCompensationOutboxAndRefundInbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("booking")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorReference")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_reference_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("PartyReference")
                        .HasColumnType("uuid")
                        .HasColumnName("party_reference_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Instant>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.Property<Guid>("TourDeparture")
                        .HasColumnType("uuid")
                        .HasColumnName("tour_departure_id");

                    b.HasKey("Id");

                    b.HasIndex("TourDeparture")
                        .HasDatabaseName("ix_bookings_tour_departure_id");

                    b.ToTable("bookings", "booking", t =>
                        {
                            t.HasCheckConstraint("ck_bookings_source_context", "(source_kind = 0 AND agency_profile_id IS NULL AND agency_offer_id IS NULL) OR (source_kind = 1 AND agency_profile_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.BookingAccessCredential", b =>
                {
                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("BookingId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_booking_access_credentials_token_hash");

                    b.ToTable("booking_access_credentials", "booking");
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.BookingConfirmationRecoveryIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Instant>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<int>("Reason")
                        .HasColumnType("integer")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ux_booking_confirmation_recovery_issues_booking_id");

                    b.ToTable("booking_confirmation_recovery_issues", "booking", t =>
                        {
                            t.HasCheckConstraint("ck_booking_confirmation_recovery_issues_reason", "reason IN (1, 2, 3, 4, 5, 6)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.BookingMonetaryComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId")
                        .HasDatabaseName("ix_booking_monetary_snapshot_components_snapshot_id");

                    b.HasIndex("SnapshotId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_booking_monetary_snapshot_components_snapshot_sort");

                    b.ToTable("booking_monetary_snapshot_components", "booking");
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.BookingMonetarySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Instant>("QuoteExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quote_expires_at");

                    b.Property<Guid>("QuoteReference")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_reference_id");

                    b.Property<Instant>("QuotedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quoted_at");

                    b.Property<Guid>("SourcePriceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_price_id");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("snapshot_target_type");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ux_booking_monetary_snapshots_booking_id");

                    b.ToTable("booking_monetary_snapshots", "booking", t =>
                        {
                            t.HasCheckConstraint("ck_booking_monetary_snapshots_quote_expires_after_quoted", "quote_expires_at > quoted_at");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.BookingPassenger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("traveler_category");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("family_name");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("given_name");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_booking_passengers_booking_id");

                    b.ToTable("booking_passengers", "booking");
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.BookingPublicIdempotencyRecord", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("IdempotencyKey");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_booking_public_idempotency_booking_id");

                    b.ToTable("booking_public_idempotency", "booking");
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.BookingRefundInvariantIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Instant>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<Guid>("RefundId")
                        .HasColumnType("uuid")
                        .HasColumnName("refund_id");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("RefundId")
                        .IsUnique()
                        .HasDatabaseName("ux_booking_refund_invariant_issues_refund_id");

                    b.ToTable("booking_refund_invariant_issues", "booking", t =>
                        {
                            t.HasCheckConstraint("ck_booking_refund_invariant_issues_kind", "kind IN (1)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.CapacityHold", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<int>("ObservedConfiguredCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("observed_configured_capacity");

                    b.Property<int>("SeatCount")
                        .HasColumnType("integer")
                        .HasColumnName("seat_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Instant>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.Property<Guid>("TourDeparture")
                        .HasColumnType("uuid")
                        .HasColumnName("tour_departure_id");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ux_capacity_holds_one_active_per_booking")
                        .HasFilter("status = 1");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_capacity_holds_idempotency_key");

                    b.HasIndex("TourDeparture")
                        .HasDatabaseName("ix_capacity_holds_tour_departure_id");

                    b.ToTable("capacity_holds", "booking", t =>
                        {
                            t.HasCheckConstraint("ck_capacity_holds_expires_after_created", "expires_at > created_at");

                            t.HasCheckConstraint("ck_capacity_holds_observed_capacity_positive", "observed_configured_capacity > 0");

                            t.HasCheckConstraint("ck_capacity_holds_seat_count_positive", "seat_count > 0");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.DepartureCapacityAccount", b =>
                {
                    b.Property<Guid>("TourDeparture")
                        .HasColumnType("uuid")
                        .HasColumnName("tour_departure_id");

                    b.Property<int>("ActiveSeats")
                        .HasColumnType("integer")
                        .HasColumnName("active_seats");

                    b.Property<int>("ConsumedSeats")
                        .HasColumnType("integer")
                        .HasColumnName("consumed_seats");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("TourDeparture");

                    b.ToTable("departure_capacity_accounts", "booking", t =>
                        {
                            t.HasCheckConstraint("ck_departure_capacity_accounts_active_seats_nonnegative", "active_seats >= 0");

                            t.HasCheckConstraint("ck_departure_capacity_accounts_consumed_seats_nonnegative", "consumed_seats >= 0");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Infrastructure.BookingOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("message_type");

                    b.Property<Instant>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Instant?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_booking_outbox_messages_processed_at");

                    b.ToTable("outbox_messages", "booking");
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Infrastructure.PaymentSuccessInboxRecord", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<Instant>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("PaymentId");

                    b.ToTable("payment_success_inbox", "booking");
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Infrastructure.RefundSuccessInboxRecord", b =>
                {
                    b.Property<Guid>("RefundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("refund_id");

                    b.Property<Instant>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("RefundId");

                    b.ToTable("refund_success_inbox", "booking");
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.Booking", b =>
                {
                    b.OwnsOne("TravelCore.Modules.Booking.Domain.BookingContactSnapshot", "Contact", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DisplayName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("contact_display_name");

                            b1.Property<string>("Email")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("contact_email");

                            b1.Property<string>("NormalizedEmail")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("contact_normalized_email");

                            b1.Property<string>("Phone")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("contact_phone");

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings", "booking");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("TravelCore.Modules.Booking.Domain.BookingSourceContext", "Source", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("AgencyOffer")
                                .HasColumnType("uuid")
                                .HasColumnName("agency_offer_id");

                            b1.Property<Guid?>("AgencyProfile")
                                .HasColumnType("uuid")
                                .HasColumnName("agency_profile_id");

                            b1.Property<short>("Kind")
                                .HasColumnType("smallint")
                                .HasColumnName("source_kind");

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings", "booking");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.Navigation("Contact");

                    b.Navigation("Source")
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.BookingAccessCredential", b =>
                {
                    b.HasOne("TravelCore.Modules.Booking.Domain.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.BookingConfirmationRecoveryIssue", b =>
                {
                    b.HasOne("TravelCore.Modules.Booking.Domain.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.BookingMonetaryComponent", b =>
                {
                    b.HasOne("TravelCore.Modules.Booking.Domain.BookingMonetarySnapshot", null)
                        .WithMany("Components")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TravelCore.Money.Money", "Money", b1 =>
                        {
                            b1.Property<Guid>("BookingMonetaryComponentId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(24,8)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("currency_code");

                            b1.HasKey("BookingMonetaryComponentId");

                            b1.ToTable("booking_monetary_snapshot_components", "booking");

                            b1.WithOwner()
                                .HasForeignKey("BookingMonetaryComponentId");
                        });

                    b.Navigation("Money")
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.BookingMonetarySnapshot", b =>
                {
                    b.HasOne("TravelCore.Modules.Booking.Domain.Booking", null)
                        .WithOne("MonetarySnapshot")
                        .HasForeignKey("TravelCore.Modules.Booking.Domain.BookingMonetarySnapshot", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TravelCore.Money.Money", "Total", b1 =>
                        {
                            b1.Property<Guid>("BookingMonetarySnapshotId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(24,8)")
                                .HasColumnName("total_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("currency_code");

                            b1.HasKey("BookingMonetarySnapshotId");

                            b1.ToTable("booking_monetary_snapshots", "booking");

                            b1.WithOwner()
                                .HasForeignKey("BookingMonetarySnapshotId");
                        });

                    b.Navigation("Total")
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.BookingPassenger", b =>
                {
                    b.HasOne("TravelCore.Modules.Booking.Domain.Booking", null)
                        .WithMany("Passengers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.BookingPublicIdempotencyRecord", b =>
                {
                    b.HasOne("TravelCore.Modules.Booking.Domain.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.BookingRefundInvariantIssue", b =>
                {
                    b.HasOne("TravelCore.Modules.Booking.Domain.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.CapacityHold", b =>
                {
                    b.HasOne("TravelCore.Modules.Booking.Domain.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.Booking", b =>
                {
                    b.Navigation("MonetarySnapshot");

                    b.Navigation("Passengers");
                });

            modelBuilder.Entity("TravelCore.Modules.Booking.Domain.BookingMonetarySnapshot", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
