// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCore.Modules.Content.Infrastructure;

#nullable disable

namespace TravelCore.Modules.Content.Infrastructure.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    partial class ContentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.Article", b =>
                {
                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_item_id");

                    b.HasKey("ContentItemId");

                    b.ToTable("articles", "content");
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.ContentBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_item_id");

                    b.Property<Guid?>("ContentItemId2")
                        .HasColumnType("uuid");

                    b.Property<short?>("HeadingLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("heading_level");

                    b.Property<string>("Href")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("href");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<Guid?>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Text")
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("ContentItemId2");

                    b.HasIndex("Kind")
                        .HasDatabaseName("ix_content_blocks_kind");

                    b.HasIndex("MediaAssetId")
                        .HasDatabaseName("ix_content_blocks_media_asset_id");

                    b.HasIndex("ContentItemId", "SortOrder")
                        .HasDatabaseName("ix_content_blocks_item_sort");

                    b.ToTable("content_blocks", "content");
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.ContentBlockFaqItem", b =>
                {
                    b.Property<Guid>("BlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("block_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("answer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("question");

                    b.HasKey("BlockId", "SortOrder");

                    b.ToTable("content_block_faq_items", "content");
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.ContentBlockGalleryItem", b =>
                {
                    b.Property<Guid>("BlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("block_id");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("BlockId", "MediaAssetId");

                    b.HasIndex("BlockId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_content_block_gallery_items_sort");

                    b.ToTable("content_block_gallery_items", "content");
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.ContentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("english_name");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_content_categories_code");

                    b.ToTable("content_categories", "content");
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.ContentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("english_name");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_content_items_code");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_content_items_created_at");

                    b.HasIndex("Kind")
                        .HasDatabaseName("ix_content_items_kind");

                    b.ToTable("content_items", "content");
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.ContentItemCategory", b =>
                {
                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_item_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("ContentItemId", "CategoryId");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_content_item_categories_category_id");

                    b.ToTable("content_item_categories", "content");
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.ContentItemDestination", b =>
                {
                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_item_id");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_id");

                    b.HasKey("ContentItemId", "DestinationId");

                    b.HasIndex("DestinationId")
                        .HasDatabaseName("ix_content_item_destinations_destination_id");

                    b.ToTable("content_item_destinations", "content");
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.ContentItemTag", b =>
                {
                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_item_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("ContentItemId", "TagId");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_content_item_tags_tag_id");

                    b.ToTable("content_item_tags", "content");
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.ContentItemTranslation", b =>
                {
                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_item_id");

                    b.Property<string>("LocaleCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale_code");

                    b.Property<string>("Body")
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)")
                        .HasColumnName("body");

                    b.Property<string>("Excerpt")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("excerpt");

                    b.Property<string>("Slug")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ContentItemId", "LocaleCode");

                    b.HasIndex("LocaleCode")
                        .HasDatabaseName("ix_content_item_translations_locale_code");

                    b.HasIndex("LocaleCode", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_content_item_translations_locale_slug")
                        .HasFilter("slug IS NOT NULL");

                    b.ToTable("content_item_translations", "content");
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.ContentTag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("english_name");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_content_tags_code");

                    b.ToTable("content_tags", "content");
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.Guide", b =>
                {
                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_item_id");

                    b.HasKey("ContentItemId");

                    b.ToTable("guides", "content");
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.LandingPage", b =>
                {
                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_item_id");

                    b.HasKey("ContentItemId");

                    b.ToTable("landing_pages", "content");
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.Article", b =>
                {
                    b.HasOne("TravelCore.Modules.Content.Domain.ContentItem", null)
                        .WithOne("Article")
                        .HasForeignKey("TravelCore.Modules.Content.Domain.Article", "ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.ContentBlock", b =>
                {
                    b.HasOne("TravelCore.Modules.Content.Domain.ContentItem", null)
                        .WithMany("Blocks")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelCore.Modules.Content.Domain.ContentItem", null)
                        .WithMany("BlocksOrdered")
                        .HasForeignKey("ContentItemId2");
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.ContentBlockFaqItem", b =>
                {
                    b.HasOne("TravelCore.Modules.Content.Domain.ContentBlock", null)
                        .WithMany("FaqItems")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.ContentBlockGalleryItem", b =>
                {
                    b.HasOne("TravelCore.Modules.Content.Domain.ContentBlock", null)
                        .WithMany("GalleryItems")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.ContentItemCategory", b =>
                {
                    b.HasOne("TravelCore.Modules.Content.Domain.ContentCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelCore.Modules.Content.Domain.ContentItem", null)
                        .WithMany("Categories")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.ContentItemDestination", b =>
                {
                    b.HasOne("TravelCore.Modules.Content.Domain.ContentItem", null)
                        .WithMany("Destinations")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.ContentItemTag", b =>
                {
                    b.HasOne("TravelCore.Modules.Content.Domain.ContentItem", null)
                        .WithMany("Tags")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelCore.Modules.Content.Domain.ContentTag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.ContentItemTranslation", b =>
                {
                    b.HasOne("TravelCore.Modules.Content.Domain.ContentItem", null)
                        .WithMany("Translations")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.Guide", b =>
                {
                    b.HasOne("TravelCore.Modules.Content.Domain.ContentItem", null)
                        .WithOne("Guide")
                        .HasForeignKey("TravelCore.Modules.Content.Domain.Guide", "ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.LandingPage", b =>
                {
                    b.HasOne("TravelCore.Modules.Content.Domain.ContentItem", null)
                        .WithOne("LandingPage")
                        .HasForeignKey("TravelCore.Modules.Content.Domain.LandingPage", "ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.ContentBlock", b =>
                {
                    b.Navigation("FaqItems");

                    b.Navigation("GalleryItems");
                });

            modelBuilder.Entity("TravelCore.Modules.Content.Domain.ContentItem", b =>
                {
                    b.Navigation("Article");

                    b.Navigation("Blocks");

                    b.Navigation("BlocksOrdered");

                    b.Navigation("Categories");

                    b.Navigation("Destinations");

                    b.Navigation("Guide");

                    b.Navigation("LandingPage");

                    b.Navigation("Tags");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
