// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCore.Modules.CommercialFinance.Infrastructure;

#nullable disable

namespace TravelCore.Modules.CommercialFinance.Infrastructure.Migrations
{
    [DbContext(typeof(CommercialFinanceDbContext))]
    [Migration("20260822130100_P39CommercialFinancePersistenceFoundation")]
    partial class P39CommercialFinancePersistenceFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("commercial_finance")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelCore.Modules.CommercialFinance.Domain.AgencyOfferCommissionOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyOfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_offer_id");

                    b.Property<Guid>("CommissionAgreementId")
                        .HasColumnType("uuid")
                        .HasColumnName("commission_agreement_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AgencyOfferId")
                        .IsUnique()
                        .HasDatabaseName("ux_agency_offer_commission_overrides_agency_offer_id");

                    b.HasIndex("CommissionAgreementId");

                    b.ToTable("agency_offer_commission_overrides", "commercial_finance");
                });

            modelBuilder.Entity("TravelCore.Modules.CommercialFinance.Domain.CommercialFinanceEventConsumptionRecord", b =>
                {
                    b.Property<short>("SourceKind")
                        .HasColumnType("smallint")
                        .HasColumnName("source_kind");

                    b.Property<string>("SourceEventKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_event_key");

                    b.Property<Instant>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<Guid>("ObligationId")
                        .HasColumnType("uuid")
                        .HasColumnName("obligation_id");

                    b.HasKey("SourceKind", "SourceEventKey");

                    b.HasIndex("ObligationId");

                    b.ToTable("event_consumption_records", "commercial_finance");
                });

            modelBuilder.Entity("TravelCore.Modules.CommercialFinance.Domain.CommercialObligation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgencyOfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_offer_id");

                    b.Property<Guid>("AgencyProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_profile_id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EvidenceSnapshotHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("evidence_snapshot_hash");

                    b.Property<short>("LifecycleState")
                        .HasColumnType("smallint")
                        .HasColumnName("lifecycle_state");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("SourceEventKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_event_key");

                    b.Property<Instant>("StateChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("state_changed_at");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SourceEventKey")
                        .IsUnique()
                        .HasDatabaseName("ux_commercial_obligations_source_event_key");

                    b.HasIndex("AgencyProfileId", "LifecycleState")
                        .HasDatabaseName("ix_commercial_obligations_agency_profile_lifecycle");

                    b.ToTable("commercial_obligations", "commercial_finance");
                });

            modelBuilder.Entity("TravelCore.Modules.CommercialFinance.Domain.CommissionAgreement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_profile_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<Instant?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<short>("MarketPolicy")
                        .HasColumnType("smallint")
                        .HasColumnName("market_policy");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AgencyProfileId")
                        .HasDatabaseName("ix_commission_agreements_agency_profile_id");

                    b.ToTable("commission_agreements", "commercial_finance");
                });

            modelBuilder.Entity("TravelCore.Modules.CommercialFinance.Domain.PayoutInstruction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ApprovalRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("approval_required");

                    b.Property<Instant?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SettlementRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("settlement_record_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SettlementRecordId");

                    b.ToTable("payout_instructions", "commercial_finance");
                });

            modelBuilder.Entity("TravelCore.Modules.CommercialFinance.Domain.SettlementPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_profile_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<Instant>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AgencyProfileId", "Status")
                        .HasDatabaseName("ix_settlement_periods_agency_profile_status");

                    b.ToTable("settlement_periods", "commercial_finance");
                });

            modelBuilder.Entity("TravelCore.Modules.CommercialFinance.Domain.SettlementRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ApprovalRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("approval_required");

                    b.Property<Instant?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SettlementPeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("settlement_period_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SettlementPeriodId");

                    b.ToTable("settlement_records", "commercial_finance");
                });

            modelBuilder.Entity("TravelCore.Modules.CommercialFinance.Domain.AgencyOfferCommissionOverride", b =>
                {
                    b.HasOne("TravelCore.Modules.CommercialFinance.Domain.CommissionAgreement", null)
                        .WithMany()
                        .HasForeignKey("CommissionAgreementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.CommercialFinance.Domain.CommercialFinanceEventConsumptionRecord", b =>
                {
                    b.HasOne("TravelCore.Modules.CommercialFinance.Domain.CommercialObligation", null)
                        .WithMany()
                        .HasForeignKey("ObligationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.CommercialFinance.Domain.CommercialObligation", b =>
                {
                    b.OwnsOne("TravelCore.Money.Money", "AmountSnapshot", b1 =>
                        {
                            b1.Property<Guid>("CommercialObligationId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(24,8)")
                                .HasColumnName("amount_snapshot_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("amount_snapshot_currency_code");

                            b1.HasKey("CommercialObligationId");

                            b1.ToTable("commercial_obligations", "commercial_finance");

                            b1.WithOwner()
                                .HasForeignKey("CommercialObligationId");
                        });

                    b.Navigation("AmountSnapshot");
                });

            modelBuilder.Entity("TravelCore.Modules.CommercialFinance.Domain.PayoutInstruction", b =>
                {
                    b.HasOne("TravelCore.Modules.CommercialFinance.Domain.SettlementRecord", null)
                        .WithMany()
                        .HasForeignKey("SettlementRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("TravelCore.Money.Money", "PayoutAmountSnapshot", b1 =>
                        {
                            b1.Property<Guid>("PayoutInstructionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(24,8)")
                                .HasColumnName("payout_amount_snapshot_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("payout_amount_snapshot_currency_code");

                            b1.HasKey("PayoutInstructionId");

                            b1.ToTable("payout_instructions", "commercial_finance");

                            b1.WithOwner()
                                .HasForeignKey("PayoutInstructionId");
                        });

                    b.Navigation("PayoutAmountSnapshot");
                });

            modelBuilder.Entity("TravelCore.Modules.CommercialFinance.Domain.SettlementRecord", b =>
                {
                    b.HasOne("TravelCore.Modules.CommercialFinance.Domain.SettlementPeriod", null)
                        .WithMany()
                        .HasForeignKey("SettlementPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
