// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCore.Modules.ReferenceData.Infrastructure;

#nullable disable

namespace TravelCore.Modules.ReferenceData.Infrastructure.Migrations
{
    [DbContext(typeof(ReferenceDataDbContext))]
    [Migration("20260815224817_InitialReferenceDataPersistence")]
    partial class InitialReferenceDataPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reference_data")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelCore.Modules.ReferenceData.Domain.CountryCatalogEntry", b =>
                {
                    b.Property<string>("Alpha2Code")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("alpha2_code");

                    b.Property<string>("Alpha3Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("alpha3_code");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("english_name");

                    b.Property<string>("NumericCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("numeric_code");

                    b.HasKey("Alpha2Code");

                    b.HasIndex("Alpha3Code")
                        .IsUnique()
                        .HasDatabaseName("ix_countries_alpha3_code");

                    b.ToTable("countries", "reference_data");
                });

            modelBuilder.Entity("TravelCore.Modules.ReferenceData.Domain.CurrencyCatalogEntry", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("code");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("english_name");

                    b.Property<int>("MinorUnits")
                        .HasColumnType("integer")
                        .HasColumnName("minor_units");

                    b.Property<string>("Symbol")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("symbol");

                    b.HasKey("Code");

                    b.ToTable("currencies", "reference_data");
                });

            modelBuilder.Entity("TravelCore.Modules.ReferenceData.Domain.LocaleCatalogEntry", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("english_name");

                    b.HasKey("Code");

                    b.ToTable("locales", "reference_data");
                });

            modelBuilder.Entity("TravelCore.Modules.ReferenceData.Domain.TimeZoneCatalogEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("english_name");

                    b.HasKey("Id");

                    b.ToTable("time_zones", "reference_data");
                });
#pragma warning restore 612, 618
        }
    }
}
