// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCore.Modules.DynamicPackage.Infrastructure;

#nullable disable

namespace TravelCore.Modules.DynamicPackage.Infrastructure.Migrations
{
    [DbContext(typeof(DynamicPackageDbContext))]
    [Migration("20260819100000_InitialDynamicPackageScaffolding")]
    partial class InitialDynamicPackageScaffolding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dynamic_package")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
