// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCore.Modules.HotelBooking.Infrastructure;

#nullable disable

namespace TravelCore.Modules.HotelBooking.Infrastructure.Migrations
{
    [DbContext(typeof(HotelBookingDbContext))]
    [Migration("20260818174737_AddHotelBookingCancellation")]
    partial class AddHotelBookingCancellation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hotel_booking")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelAvailabilityHold", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<Instant?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<Instant?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("HotelBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_booking_id");

                    b.Property<Instant?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<Instant>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("SourceHoldReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_hold_reference");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_key");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("HotelBookingId")
                        .IsUnique()
                        .HasDatabaseName("ux_hotel_availability_holds_one_unresolved")
                        .HasFilter("status IN (1, 2)");

                    b.HasIndex("SourceKey", "SourceHoldReference")
                        .IsUnique()
                        .HasDatabaseName("ux_hotel_availability_holds_source_ref")
                        .HasFilter("source_hold_reference IS NOT NULL");

                    b.ToTable("hotel_availability_holds", "hotel_booking", t =>
                        {
                            t.HasCheckConstraint("ck_hotel_availability_holds_active_expiry", "(status <> 2) OR (expires_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_hotel_availability_holds_status", "status IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelAvailabilityHoldIdempotencyRecord", b =>
                {
                    b.Property<Guid>("HotelBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_booking_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HoldId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_availability_hold_id");

                    b.HasKey("HotelBookingId", "IdempotencyKey");

                    b.ToTable("hotel_hold_idempotency", "hotel_booking");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelAvailabilityHoldRoom", b =>
                {
                    b.Property<Guid>("HoldId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_availability_hold_id");

                    b.Property<Guid>("RoomReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_reservation_id");

                    b.Property<string>("SelectionReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("selection_reference");

                    b.HasKey("HoldId", "RoomReservationId");

                    b.ToTable("hotel_availability_hold_rooms", "hotel_booking");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<LocalDate>("CheckInDate")
                        .HasColumnType("date")
                        .HasColumnName("check_in_date");

                    b.Property<LocalDate>("CheckOutDate")
                        .HasColumnType("date")
                        .HasColumnName("check_out_date");

                    b.Property<Instant?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid>("Place")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("hotel_bookings", "hotel_booking", t =>
                        {
                            t.HasCheckConstraint("ck_hotel_bookings_checkout_after_checkin", "check_out_date > check_in_date");

                            t.HasCheckConstraint("ck_hotel_bookings_status", "status IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelBookingCancellation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<short>("FinancialOutcome")
                        .HasColumnType("smallint")
                        .HasColumnName("financial_outcome");

                    b.Property<Guid>("HotelBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_booking_id");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<decimal>("PenaltyAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("penalty_amount");

                    b.Property<decimal>("RefundAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("refund_amount");

                    b.Property<Instant>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("HotelBookingId")
                        .IsUnique()
                        .HasDatabaseName("ux_hotel_booking_cancellations_hotel_booking_id");

                    b.ToTable("hotel_booking_cancellations", "hotel_booking", t =>
                        {
                            t.HasCheckConstraint("ck_hotel_booking_cancellations_financial_outcome", "financial_outcome IN (1, 2)");

                            t.HasCheckConstraint("ck_hotel_booking_cancellations_status", "status IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelBookingCancellationIdempotencyRecord", b =>
                {
                    b.Property<Guid>("HotelBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_booking_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_supplier_cancellation_attempt_id");

                    b.Property<Guid>("CancellationId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_booking_cancellation_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("HotelBookingId", "IdempotencyKey");

                    b.HasIndex("CancellationId");

                    b.ToTable("hotel_booking_cancellation_idempotency", "hotel_booking");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelBookingGuest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AgeAtCheckIn")
                        .HasColumnType("integer")
                        .HasColumnName("age_at_check_in");

                    b.Property<short>("Category")
                        .HasColumnType("smallint")
                        .HasColumnName("category");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("family_name");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("given_name");

                    b.Property<Guid>("HotelBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_booking_id");

                    b.Property<bool>("IsLeadGuest")
                        .HasColumnType("boolean")
                        .HasColumnName("is_lead_guest");

                    b.Property<Guid>("RoomReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_reservation_id");

                    b.HasKey("Id");

                    b.HasIndex("HotelBookingId")
                        .IsUnique()
                        .HasDatabaseName("ux_hotel_booking_guests_one_lead")
                        .HasFilter("is_lead_guest = TRUE");

                    b.HasIndex("RoomReservationId");

                    b.ToTable("hotel_booking_guests", "hotel_booking", t =>
                        {
                            t.HasCheckConstraint("ck_hotel_booking_guests_age_by_category", "(category = 1 AND age_at_check_in IS NULL) OR (category = 2 AND age_at_check_in IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelBookingMonetarySnapshot", b =>
                {
                    b.Property<Guid>("HotelRateOfferSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_rate_offer_snapshot_id");

                    b.Property<Guid>("HotelBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_booking_id");

                    b.HasKey("HotelRateOfferSnapshotId");

                    b.HasIndex("HotelBookingId")
                        .IsUnique()
                        .HasDatabaseName("ux_hotel_booking_monetary_snapshots_hotel_booking_id");

                    b.ToTable("hotel_booking_monetary_snapshots", "hotel_booking");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelBookingPaymentCompensationEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<Guid>("HotelBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_booking_id");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<short>("Reason")
                        .HasColumnType("smallint")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("HotelBookingId")
                        .IsUnique()
                        .HasDatabaseName("ux_hotel_booking_payment_compensation_evidence_hotel_booking_id");

                    b.ToTable("hotel_booking_payment_compensation_evidence", "hotel_booking", t =>
                        {
                            t.HasCheckConstraint("ck_hotel_booking_payment_compensation_reason", "reason IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelBookingPaymentEvidence", b =>
                {
                    b.Property<Guid>("HotelBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_booking_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<Instant>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("HotelBookingId");

                    b.HasIndex("PaymentId")
                        .IsUnique()
                        .HasDatabaseName("ux_hotel_booking_payment_evidence_payment_id");

                    b.ToTable("hotel_booking_payment_evidence", "hotel_booking");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelBookingReconciliationIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_supplier_reservation_attempt_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("detail");

                    b.Property<Guid>("HotelBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_booking_id");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_supplier_reservation_id");

                    b.HasKey("Id");

                    b.HasIndex("HotelBookingId")
                        .HasDatabaseName("ix_hotel_booking_reconciliation_issues_hotel_booking_id");

                    b.ToTable("hotel_booking_reconciliation_issues", "hotel_booking", t =>
                        {
                            t.HasCheckConstraint("ck_hotel_booking_reconciliation_issues_kind", "kind IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelBookingRefundInvariantIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<Guid>("HotelBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_booking_id");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<Guid>("RefundId")
                        .HasColumnType("uuid")
                        .HasColumnName("refund_id");

                    b.HasKey("Id");

                    b.HasIndex("HotelBookingId");

                    b.HasIndex("RefundId")
                        .IsUnique()
                        .HasDatabaseName("ux_hotel_booking_refund_invariant_issues_refund_id");

                    b.ToTable("hotel_booking_refund_invariant_issues", "hotel_booking", t =>
                        {
                            t.HasCheckConstraint("ck_hotel_booking_refund_invariant_kind", "kind IN (1, 2)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelCancellationPenaltyRule", b =>
                {
                    b.Property<Guid>("HotelRateOfferSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_rate_offer_snapshot_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Instant>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<Instant?>("EffectiveUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_until");

                    b.HasKey("HotelRateOfferSnapshotId", "Ordinal");

                    b.ToTable("hotel_cancellation_penalty_rules", "hotel_booking");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelCancellationPolicySnapshot", b =>
                {
                    b.Property<Guid>("HotelRateOfferSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_rate_offer_snapshot_id");

                    b.Property<string>("PropertyTimeZoneId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("property_time_zone_id");

                    b.Property<string>("PublicExplanation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("public_explanation");

                    b.HasKey("HotelRateOfferSnapshotId");

                    b.ToTable("hotel_cancellation_policy_snapshots", "hotel_booking");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelChargeComponentSnapshot", b =>
                {
                    b.Property<Guid>("HotelRateOfferSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_rate_offer_snapshot_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.HasKey("HotelRateOfferSnapshotId", "Ordinal");

                    b.ToTable("hotel_charge_component_snapshots", "hotel_booking");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelRateOfferIdempotencyRecord", b =>
                {
                    b.Property<Guid>("HotelBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_booking_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_rate_offer_snapshot_id");

                    b.HasKey("HotelBookingId", "IdempotencyKey");

                    b.ToTable("hotel_rate_offer_idempotency", "hotel_booking");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelRateOfferSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<LocalDate>("CheckInDate")
                        .HasColumnType("date")
                        .HasColumnName("check_in_date");

                    b.Property<LocalDate>("CheckOutDate")
                        .HasColumnType("date")
                        .HasColumnName("check_out_date");

                    b.Property<Guid>("HotelBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_booking_id");

                    b.Property<Instant?>("OfferExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("offer_expires_at");

                    b.Property<Guid>("Place")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<Instant>("QuotedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quoted_at");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_key");

                    b.Property<string>("SourceOfferReference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_offer_reference");

                    b.HasKey("Id");

                    b.HasIndex("HotelBookingId")
                        .IsUnique()
                        .HasDatabaseName("ux_hotel_rate_offer_snapshots_hotel_booking_id");

                    b.ToTable("hotel_rate_offer_snapshots", "hotel_booking");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelRoomRateSnapshot", b =>
                {
                    b.Property<Guid>("HotelRateOfferSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_rate_offer_snapshot_id");

                    b.Property<Guid>("RoomReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_reservation_id");

                    b.Property<string>("AvailabilitySelectionReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("availability_selection_reference");

                    b.Property<string>("BoardBasisCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("board_basis_code");

                    b.Property<string>("SourceRateReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_rate_reference");

                    b.HasKey("HotelRateOfferSnapshotId", "RoomReservationId");

                    b.ToTable("hotel_room_rate_snapshots", "hotel_booking");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelSupplierCancellationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CancellationId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_booking_cancellation_id");

                    b.Property<Instant?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<Instant?>("InitiatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("initiated_at");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CancellationId")
                        .IsUnique()
                        .HasDatabaseName("ux_hotel_supplier_cancellation_attempts_one_unresolved")
                        .HasFilter("status IN (1, 2)");

                    b.ToTable("hotel_supplier_cancellation_attempts", "hotel_booking", t =>
                        {
                            t.HasCheckConstraint("ck_hotel_supplier_cancellation_attempts_status", "status IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelSupplierReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Instant?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HotelBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_booking_id");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_key");

                    b.Property<string>("SourceReservationReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_reservation_reference");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("SupplierConfirmationCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("supplier_confirmation_code");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("HotelBookingId")
                        .IsUnique()
                        .HasDatabaseName("ux_hotel_supplier_reservations_hotel_booking_id");

                    b.HasIndex("SourceKey", "SourceReservationReference")
                        .IsUnique()
                        .HasDatabaseName("ux_hotel_supplier_reservations_source_ref")
                        .HasFilter("source_reservation_reference IS NOT NULL");

                    b.ToTable("hotel_supplier_reservations", "hotel_booking", t =>
                        {
                            t.HasCheckConstraint("ck_hotel_supplier_reservations_status", "status IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelSupplierReservationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<Instant?>("InitiatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("initiated_at");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_supplier_reservation_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId")
                        .IsUnique()
                        .HasDatabaseName("ux_hotel_supplier_reservation_attempts_one_unresolved")
                        .HasFilter("status IN (1, 2)");

                    b.ToTable("hotel_supplier_reservation_attempts", "hotel_booking", t =>
                        {
                            t.HasCheckConstraint("ck_hotel_supplier_reservation_attempts_status", "status IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelSupplierReservationIdempotencyRecord", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_supplier_reservation_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_supplier_reservation_attempt_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("ReservationId", "IdempotencyKey");

                    b.ToTable("hotel_supplier_reservation_idempotency", "hotel_booking");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.RoomReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("HotelBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_booking_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.HasKey("Id");

                    b.HasIndex("HotelBookingId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_room_reservations_booking_ordinal");

                    b.ToTable("room_reservations", "hotel_booking");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Infrastructure.HotelBookingOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("message_type");

                    b.Property<Instant>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Instant?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_hotel_booking_outbox_messages_processed_at");

                    b.ToTable("outbox_messages", "hotel_booking");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Infrastructure.HotelBookingPaymentSuccessInboxRecord", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<Instant>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("PaymentId");

                    b.ToTable("payment_success_inbox", "hotel_booking");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Infrastructure.HotelBookingRefundSuccessInboxRecord", b =>
                {
                    b.Property<Guid>("RefundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("refund_id");

                    b.Property<Instant>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("RefundId");

                    b.ToTable("refund_success_inbox", "hotel_booking");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelAvailabilityHold", b =>
                {
                    b.HasOne("TravelCore.Modules.HotelBooking.Domain.HotelBooking", null)
                        .WithMany()
                        .HasForeignKey("HotelBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelAvailabilityHoldIdempotencyRecord", b =>
                {
                    b.HasOne("TravelCore.Modules.HotelBooking.Domain.HotelBooking", null)
                        .WithMany()
                        .HasForeignKey("HotelBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelAvailabilityHoldRoom", b =>
                {
                    b.HasOne("TravelCore.Modules.HotelBooking.Domain.HotelAvailabilityHold", null)
                        .WithMany("Rooms")
                        .HasForeignKey("HoldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelBooking", b =>
                {
                    b.OwnsOne("TravelCore.Modules.HotelBooking.Domain.HotelBookingContactSnapshot", "Contact", b1 =>
                        {
                            b1.Property<Guid>("HotelBookingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("contact_email");

                            b1.Property<string>("NormalizedEmail")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("contact_normalized_email");

                            b1.Property<string>("Phone")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("contact_phone");

                            b1.HasKey("HotelBookingId");

                            b1.ToTable("hotel_bookings", "hotel_booking");

                            b1.WithOwner()
                                .HasForeignKey("HotelBookingId");
                        });

                    b.Navigation("Contact")
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelBookingCancellation", b =>
                {
                    b.HasOne("TravelCore.Modules.HotelBooking.Domain.HotelBooking", null)
                        .WithMany()
                        .HasForeignKey("HotelBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelBookingCancellationIdempotencyRecord", b =>
                {
                    b.HasOne("TravelCore.Modules.HotelBooking.Domain.HotelBookingCancellation", null)
                        .WithMany()
                        .HasForeignKey("CancellationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelBookingGuest", b =>
                {
                    b.HasOne("TravelCore.Modules.HotelBooking.Domain.RoomReservation", null)
                        .WithMany("Guests")
                        .HasForeignKey("RoomReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelBookingMonetarySnapshot", b =>
                {
                    b.HasOne("TravelCore.Modules.HotelBooking.Domain.HotelRateOfferSnapshot", null)
                        .WithOne("Monetary")
                        .HasForeignKey("TravelCore.Modules.HotelBooking.Domain.HotelBookingMonetarySnapshot", "HotelRateOfferSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TravelCore.Money.Money", "PayableAtProperty", b1 =>
                        {
                            b1.Property<Guid>("HotelBookingMonetarySnapshotHotelRateOfferSnapshotId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(24,8)")
                                .HasColumnName("payable_at_property_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("payable_at_property_currency_code");

                            b1.HasKey("HotelBookingMonetarySnapshotHotelRateOfferSnapshotId");

                            b1.ToTable("hotel_booking_monetary_snapshots", "hotel_booking");

                            b1.WithOwner()
                                .HasForeignKey("HotelBookingMonetarySnapshotHotelRateOfferSnapshotId");
                        });

                    b.OwnsOne("TravelCore.Money.Money", "PayableNow", b1 =>
                        {
                            b1.Property<Guid>("HotelBookingMonetarySnapshotHotelRateOfferSnapshotId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(24,8)")
                                .HasColumnName("payable_now_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("payable_now_currency_code");

                            b1.HasKey("HotelBookingMonetarySnapshotHotelRateOfferSnapshotId");

                            b1.ToTable("hotel_booking_monetary_snapshots", "hotel_booking");

                            b1.WithOwner()
                                .HasForeignKey("HotelBookingMonetarySnapshotHotelRateOfferSnapshotId");
                        });

                    b.OwnsOne("TravelCore.Money.Money", "Total", b1 =>
                        {
                            b1.Property<Guid>("HotelBookingMonetarySnapshotHotelRateOfferSnapshotId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(24,8)")
                                .HasColumnName("total_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("currency_code");

                            b1.HasKey("HotelBookingMonetarySnapshotHotelRateOfferSnapshotId");

                            b1.ToTable("hotel_booking_monetary_snapshots", "hotel_booking");

                            b1.WithOwner()
                                .HasForeignKey("HotelBookingMonetarySnapshotHotelRateOfferSnapshotId");
                        });

                    b.Navigation("PayableAtProperty");

                    b.Navigation("PayableNow");

                    b.Navigation("Total")
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelBookingPaymentCompensationEvidence", b =>
                {
                    b.HasOne("TravelCore.Modules.HotelBooking.Domain.HotelBooking", null)
                        .WithMany()
                        .HasForeignKey("HotelBookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelBookingPaymentEvidence", b =>
                {
                    b.HasOne("TravelCore.Modules.HotelBooking.Domain.HotelBooking", null)
                        .WithMany()
                        .HasForeignKey("HotelBookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelBookingReconciliationIssue", b =>
                {
                    b.HasOne("TravelCore.Modules.HotelBooking.Domain.HotelBooking", null)
                        .WithMany()
                        .HasForeignKey("HotelBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelBookingRefundInvariantIssue", b =>
                {
                    b.HasOne("TravelCore.Modules.HotelBooking.Domain.HotelBooking", null)
                        .WithMany()
                        .HasForeignKey("HotelBookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelCancellationPenaltyRule", b =>
                {
                    b.HasOne("TravelCore.Modules.HotelBooking.Domain.HotelCancellationPolicySnapshot", null)
                        .WithMany("Rules")
                        .HasForeignKey("HotelRateOfferSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TravelCore.Money.Money", "Penalty", b1 =>
                        {
                            b1.Property<Guid>("HotelCancellationPenaltyRuleHotelRateOfferSnapshotId")
                                .HasColumnType("uuid");

                            b1.Property<int>("HotelCancellationPenaltyRuleOrdinal")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(24,8)")
                                .HasColumnName("penalty_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("currency_code");

                            b1.HasKey("HotelCancellationPenaltyRuleHotelRateOfferSnapshotId", "HotelCancellationPenaltyRuleOrdinal");

                            b1.ToTable("hotel_cancellation_penalty_rules", "hotel_booking");

                            b1.WithOwner()
                                .HasForeignKey("HotelCancellationPenaltyRuleHotelRateOfferSnapshotId", "HotelCancellationPenaltyRuleOrdinal");
                        });

                    b.Navigation("Penalty")
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelCancellationPolicySnapshot", b =>
                {
                    b.HasOne("TravelCore.Modules.HotelBooking.Domain.HotelRateOfferSnapshot", null)
                        .WithOne("CancellationPolicy")
                        .HasForeignKey("TravelCore.Modules.HotelBooking.Domain.HotelCancellationPolicySnapshot", "HotelRateOfferSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelChargeComponentSnapshot", b =>
                {
                    b.HasOne("TravelCore.Modules.HotelBooking.Domain.HotelBookingMonetarySnapshot", null)
                        .WithMany("Charges")
                        .HasForeignKey("HotelRateOfferSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TravelCore.Money.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("HotelChargeComponentSnapshotHotelRateOfferSnapshotId")
                                .HasColumnType("uuid");

                            b1.Property<int>("HotelChargeComponentSnapshotOrdinal")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(24,8)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("currency_code");

                            b1.HasKey("HotelChargeComponentSnapshotHotelRateOfferSnapshotId", "HotelChargeComponentSnapshotOrdinal");

                            b1.ToTable("hotel_charge_component_snapshots", "hotel_booking");

                            b1.WithOwner()
                                .HasForeignKey("HotelChargeComponentSnapshotHotelRateOfferSnapshotId", "HotelChargeComponentSnapshotOrdinal");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelRateOfferIdempotencyRecord", b =>
                {
                    b.HasOne("TravelCore.Modules.HotelBooking.Domain.HotelBooking", null)
                        .WithMany()
                        .HasForeignKey("HotelBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelRateOfferSnapshot", b =>
                {
                    b.HasOne("TravelCore.Modules.HotelBooking.Domain.HotelBooking", null)
                        .WithMany()
                        .HasForeignKey("HotelBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelRoomRateSnapshot", b =>
                {
                    b.HasOne("TravelCore.Modules.HotelBooking.Domain.HotelRateOfferSnapshot", null)
                        .WithMany("Rooms")
                        .HasForeignKey("HotelRateOfferSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TravelCore.Money.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("HotelRoomRateSnapshotHotelRateOfferSnapshotId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("HotelRoomRateSnapshotRoomReservationId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(24,8)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("currency_code");

                            b1.HasKey("HotelRoomRateSnapshotHotelRateOfferSnapshotId", "HotelRoomRateSnapshotRoomReservationId");

                            b1.ToTable("hotel_room_rate_snapshots", "hotel_booking");

                            b1.WithOwner()
                                .HasForeignKey("HotelRoomRateSnapshotHotelRateOfferSnapshotId", "HotelRoomRateSnapshotRoomReservationId");
                        });

                    b.Navigation("Amount");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelSupplierCancellationAttempt", b =>
                {
                    b.HasOne("TravelCore.Modules.HotelBooking.Domain.HotelBookingCancellation", null)
                        .WithMany("Attempts")
                        .HasForeignKey("CancellationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelSupplierReservation", b =>
                {
                    b.HasOne("TravelCore.Modules.HotelBooking.Domain.HotelBooking", null)
                        .WithMany()
                        .HasForeignKey("HotelBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelSupplierReservationAttempt", b =>
                {
                    b.HasOne("TravelCore.Modules.HotelBooking.Domain.HotelSupplierReservation", null)
                        .WithMany("Attempts")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelSupplierReservationIdempotencyRecord", b =>
                {
                    b.HasOne("TravelCore.Modules.HotelBooking.Domain.HotelSupplierReservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.RoomReservation", b =>
                {
                    b.HasOne("TravelCore.Modules.HotelBooking.Domain.HotelBooking", null)
                        .WithMany("Rooms")
                        .HasForeignKey("HotelBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelAvailabilityHold", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelBooking", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelBookingCancellation", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelBookingMonetarySnapshot", b =>
                {
                    b.Navigation("Charges");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelCancellationPolicySnapshot", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelRateOfferSnapshot", b =>
                {
                    b.Navigation("CancellationPolicy")
                        .IsRequired();

                    b.Navigation("Monetary")
                        .IsRequired();

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.HotelSupplierReservation", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("TravelCore.Modules.HotelBooking.Domain.RoomReservation", b =>
                {
                    b.Navigation("Guests");
                });
#pragma warning restore 612, 618
        }
    }
}
