// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCore.Modules.Visa.Infrastructure;

#nullable disable

namespace TravelCore.Modules.Visa.Infrastructure.Migrations
{
    [DbContext(typeof(VisaDbContext))]
    [Migration("20260817320000_AddVisaDefinitionBaseline")]
    partial class AddVisaDefinitionBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("visa")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_visa_definitions_code");

                    b.ToTable("visa_definitions", "visa");
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaDefinitionTranslation", b =>
                {
                    b.Property<Guid>("VisaDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("visa_definition_id");

                    b.Property<string>("LocaleCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("VisaDefinitionId", "LocaleCode");

                    b.HasIndex("LocaleCode")
                        .HasDatabaseName("ix_visa_definition_translations_locale_code");

                    b.ToTable("visa_definition_translations", "visa");
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaRequirementSet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VisaDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("visa_definition_id");

                    b.HasKey("Id");

                    b.HasIndex("VisaDefinitionId")
                        .HasDatabaseName("ix_visa_requirement_sets_visa_definition_id");

                    b.ToTable("visa_requirement_sets", "visa");
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaDefinitionTranslation", b =>
                {
                    b.HasOne("TravelCore.Modules.Visa.Domain.VisaDefinition", null)
                        .WithMany("Translations")
                        .HasForeignKey("VisaDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaRequirementSet", b =>
                {
                    b.HasOne("TravelCore.Modules.Visa.Domain.VisaDefinition", null)
                        .WithMany("RequirementSets")
                        .HasForeignKey("VisaDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaDefinition", b =>
                {
                    b.Navigation("RequirementSets");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
