// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCore.Modules.Visa.Infrastructure;

#nullable disable

namespace TravelCore.Modules.Visa.Infrastructure.Migrations
{
    [DbContext(typeof(VisaDbContext))]
    [Migration("20260817350000_AddVisaProcessingValidityBaseline")]
    partial class AddVisaProcessingValidityBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("visa")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaAllowedStay", b =>
                {
                    b.Property<Guid>("VisaRequirementSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("visa_requirement_set_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("unit");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("VisaRequirementSetId");

                    b.ToTable("visa_allowed_stays", "visa");
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaApplicability", b =>
                {
                    b.Property<Guid>("VisaRequirementSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("visa_requirement_set_id");

                    b.Property<string>("ApplicantCategory")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("applicant_category");

                    b.Property<string>("ApplicantNationalityCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("applicant_nationality_code");

                    b.Property<Guid>("DestinationGeographicId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_geographic_id");

                    b.Property<string>("ResidenceCountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("residence_country_code");

                    b.HasKey("VisaRequirementSetId");

                    b.HasIndex("DestinationGeographicId")
                        .HasDatabaseName("ix_visa_applicabilities_destination_geographic_id");

                    b.ToTable("visa_applicabilities", "visa");
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_visa_definitions_code");

                    b.ToTable("visa_definitions", "visa");
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaDefinitionTranslation", b =>
                {
                    b.Property<Guid>("VisaDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("visa_definition_id");

                    b.Property<string>("LocaleCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("VisaDefinitionId", "LocaleCode");

                    b.HasIndex("LocaleCode")
                        .HasDatabaseName("ix_visa_definition_translations_locale_code");

                    b.ToTable("visa_definition_translations", "visa");
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaEligibilityRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("RequirementLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("requirement_level");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Unit")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("value");

                    b.Property<Guid>("VisaRequirementSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("visa_requirement_set_id");

                    b.HasKey("Id");

                    b.HasIndex("VisaRequirementSetId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_visa_eligibility_requirements_set_code");

                    b.ToTable("visa_eligibility_requirements", "visa");
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaEligibilityRequirementTranslation", b =>
                {
                    b.Property<Guid>("EligibilityRequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("eligibility_requirement_id");

                    b.Property<string>("LocaleCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EligibilityRequirementId", "LocaleCode");

                    b.ToTable("visa_eligibility_requirement_translations", "visa");
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaEntryPolicy", b =>
                {
                    b.Property<Guid>("VisaRequirementSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("visa_requirement_set_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.HasKey("VisaRequirementSetId");

                    b.ToTable("visa_entry_policies", "visa");
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaProcessingTime", b =>
                {
                    b.Property<Guid>("VisaRequirementSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("visa_requirement_set_id");

                    b.Property<int?>("MaxValue")
                        .HasColumnType("integer")
                        .HasColumnName("max_value");

                    b.Property<int>("MinValue")
                        .HasColumnType("integer")
                        .HasColumnName("min_value");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("unit");

                    b.HasKey("VisaRequirementSetId");

                    b.ToTable("visa_processing_times", "visa");
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaRequiredDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("RequirementLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("requirement_level");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VisaRequirementSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("visa_requirement_set_id");

                    b.HasKey("Id");

                    b.HasIndex("VisaRequirementSetId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_visa_required_documents_set_code");

                    b.ToTable("visa_required_documents", "visa");
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaRequiredDocumentTranslation", b =>
                {
                    b.Property<Guid>("RequiredDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("required_document_id");

                    b.Property<string>("LocaleCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RequiredDocumentId", "LocaleCode");

                    b.ToTable("visa_required_document_translations", "visa");
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaRequirementSet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<Instant?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VisaDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("visa_definition_id");

                    b.HasKey("Id");

                    b.HasIndex("VisaDefinitionId")
                        .HasDatabaseName("ix_visa_requirement_sets_visa_definition_id");

                    b.ToTable("visa_requirement_sets", "visa");
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaValidity", b =>
                {
                    b.Property<Guid>("VisaRequirementSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("visa_requirement_set_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("unit");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("VisaRequirementSetId");

                    b.ToTable("visa_validities", "visa");
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaAllowedStay", b =>
                {
                    b.HasOne("TravelCore.Modules.Visa.Domain.VisaRequirementSet", null)
                        .WithOne("AllowedStay")
                        .HasForeignKey("TravelCore.Modules.Visa.Domain.VisaAllowedStay", "VisaRequirementSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaApplicability", b =>
                {
                    b.HasOne("TravelCore.Modules.Visa.Domain.VisaRequirementSet", null)
                        .WithOne("Applicability")
                        .HasForeignKey("TravelCore.Modules.Visa.Domain.VisaApplicability", "VisaRequirementSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaDefinitionTranslation", b =>
                {
                    b.HasOne("TravelCore.Modules.Visa.Domain.VisaDefinition", null)
                        .WithMany("Translations")
                        .HasForeignKey("VisaDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaEligibilityRequirement", b =>
                {
                    b.HasOne("TravelCore.Modules.Visa.Domain.VisaRequirementSet", null)
                        .WithMany("EligibilityRequirements")
                        .HasForeignKey("VisaRequirementSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaEligibilityRequirementTranslation", b =>
                {
                    b.HasOne("TravelCore.Modules.Visa.Domain.VisaEligibilityRequirement", null)
                        .WithMany("Translations")
                        .HasForeignKey("EligibilityRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaEntryPolicy", b =>
                {
                    b.HasOne("TravelCore.Modules.Visa.Domain.VisaRequirementSet", null)
                        .WithOne("EntryPolicy")
                        .HasForeignKey("TravelCore.Modules.Visa.Domain.VisaEntryPolicy", "VisaRequirementSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaProcessingTime", b =>
                {
                    b.HasOne("TravelCore.Modules.Visa.Domain.VisaRequirementSet", null)
                        .WithOne("ProcessingTime")
                        .HasForeignKey("TravelCore.Modules.Visa.Domain.VisaProcessingTime", "VisaRequirementSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaRequiredDocument", b =>
                {
                    b.HasOne("TravelCore.Modules.Visa.Domain.VisaRequirementSet", null)
                        .WithMany("RequiredDocuments")
                        .HasForeignKey("VisaRequirementSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaRequiredDocumentTranslation", b =>
                {
                    b.HasOne("TravelCore.Modules.Visa.Domain.VisaRequiredDocument", null)
                        .WithMany("Translations")
                        .HasForeignKey("RequiredDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaRequirementSet", b =>
                {
                    b.HasOne("TravelCore.Modules.Visa.Domain.VisaDefinition", null)
                        .WithMany("RequirementSets")
                        .HasForeignKey("VisaDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaValidity", b =>
                {
                    b.HasOne("TravelCore.Modules.Visa.Domain.VisaRequirementSet", null)
                        .WithOne("Validity")
                        .HasForeignKey("TravelCore.Modules.Visa.Domain.VisaValidity", "VisaRequirementSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaDefinition", b =>
                {
                    b.Navigation("RequirementSets");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaEligibilityRequirement", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaRequiredDocument", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("TravelCore.Modules.Visa.Domain.VisaRequirementSet", b =>
                {
                    b.Navigation("AllowedStay");

                    b.Navigation("Applicability")
                        .IsRequired();

                    b.Navigation("EligibilityRequirements");

                    b.Navigation("EntryPolicy");

                    b.Navigation("ProcessingTime");

                    b.Navigation("RequiredDocuments");

                    b.Navigation("Validity");
                });
#pragma warning restore 612, 618
        }
    }
}
