// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCore.Modules.Media.Infrastructure;

#nullable disable

namespace TravelCore.Modules.Media.Infrastructure.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    [Migration("20260816110000_AddMediaVariants")]
    partial class AddMediaVariants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("media")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelCore.Modules.Media.Domain.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("storage_key");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_media_assets_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_media_assets_status");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ux_media_assets_storage_key")
                        .HasFilter("storage_key IS NOT NULL");

                    b.ToTable("media_assets", "media");
                });

            modelBuilder.Entity("TravelCore.Modules.Media.Domain.MediaVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("failure_reason");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<short>("Profile")
                        .HasColumnType("smallint")
                        .HasColumnName("profile");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("storage_key");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ux_media_variants_storage_key")
                        .HasFilter("storage_key IS NOT NULL");

                    b.HasIndex("MediaAssetId", "Profile")
                        .IsUnique()
                        .HasDatabaseName("ux_media_variants_asset_profile");

                    b.ToTable("media_variants", "media");
                });

            modelBuilder.Entity("TravelCore.Modules.Media.Domain.MediaVariant", b =>
                {
                    b.HasOne("TravelCore.Modules.Media.Domain.MediaAsset", null)
                        .WithMany()
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_variants_media_assets");
                });
#pragma warning restore 612, 618
        }
    }
}
