// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCore.Modules.Place.Infrastructure;

#nullable disable

namespace TravelCore.Modules.Place.Infrastructure.Migrations
{
    [DbContext(typeof(PlaceDbContext))]
    [Migration("20260816200000_PlaceTranslationsDestinationLinkAndGeo")]
    partial class PlaceTranslationsDestinationLinkAndGeo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("place")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelCore.Modules.Place.Domain.Attraction", b =>
                {
                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category_code");

                    b.HasKey("PlaceId");

                    b.ToTable("attractions", "place");
                });

            modelBuilder.Entity("TravelCore.Modules.Place.Domain.Hotel", b =>
                {
                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<short?>("StarRating")
                        .HasColumnType("smallint")
                        .HasColumnName("star_rating");

                    b.HasKey("PlaceId");

                    b.ToTable("hotels", "place");
                });

            modelBuilder.Entity("TravelCore.Modules.Place.Domain.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_id");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("english_name");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_places_code");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_places_created_at");

                    b.HasIndex("DestinationId")
                        .HasDatabaseName("ix_places_destination_id");

                    b.HasIndex("Kind")
                        .HasDatabaseName("ix_places_kind");

                    b.ToTable("places", "place");
                });

            modelBuilder.Entity("TravelCore.Modules.Place.Domain.PlaceTranslation", b =>
                {
                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("LocaleCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale_code");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PlaceId", "LocaleCode");

                    b.HasIndex("LocaleCode")
                        .HasDatabaseName("ix_place_translations_locale_code");

                    b.ToTable("place_translations", "place");
                });

            modelBuilder.Entity("TravelCore.Modules.Place.Domain.Restaurant", b =>
                {
                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("CuisineType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cuisine_type");

                    b.HasKey("PlaceId");

                    b.ToTable("restaurants", "place");
                });

            modelBuilder.Entity("TravelCore.Modules.Place.Domain.Attraction", b =>
                {
                    b.HasOne("TravelCore.Modules.Place.Domain.Place", null)
                        .WithOne("Attraction")
                        .HasForeignKey("TravelCore.Modules.Place.Domain.Attraction", "PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Place.Domain.Hotel", b =>
                {
                    b.HasOne("TravelCore.Modules.Place.Domain.Place", null)
                        .WithOne("Hotel")
                        .HasForeignKey("TravelCore.Modules.Place.Domain.Hotel", "PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Place.Domain.Place", b =>
                {
                    b.OwnsOne("TravelCore.Modules.Place.Domain.PlaceAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("PlaceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AdministrativeArea")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_administrative_area");

                            b1.Property<string>("CountryCode")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("address_country_code");

                            b1.Property<string>("Line1")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_line1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_line2");

                            b1.Property<string>("Locality")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_locality");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("address_postal_code");

                            b1.HasKey("PlaceId");

                            b1.ToTable("places", "place");

                            b1.WithOwner()
                                .HasForeignKey("PlaceId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("TravelCore.Modules.Place.Domain.PlaceTranslation", b =>
                {
                    b.HasOne("TravelCore.Modules.Place.Domain.Place", null)
                        .WithMany("Translations")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Place.Domain.Restaurant", b =>
                {
                    b.HasOne("TravelCore.Modules.Place.Domain.Place", null)
                        .WithOne("Restaurant")
                        .HasForeignKey("TravelCore.Modules.Place.Domain.Restaurant", "PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Place.Domain.Place", b =>
                {
                    b.Navigation("Attraction");

                    b.Navigation("Hotel");

                    b.Navigation("Restaurant");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
