// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCore.Modules.Place.Infrastructure;

#nullable disable

namespace TravelCore.Modules.Place.Infrastructure.Migrations
{
    [DbContext(typeof(PlaceDbContext))]
    [Migration("20260816190000_AddPlaceCatalogTables")]
    partial class AddPlaceCatalogTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("place")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelCore.Modules.Place.Domain.Attraction", b =>
                {
                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category_code");

                    b.HasKey("PlaceId");

                    b.ToTable("attractions", "place");
                });

            modelBuilder.Entity("TravelCore.Modules.Place.Domain.Hotel", b =>
                {
                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<short?>("StarRating")
                        .HasColumnType("smallint")
                        .HasColumnName("star_rating");

                    b.HasKey("PlaceId");

                    b.ToTable("hotels", "place");
                });

            modelBuilder.Entity("TravelCore.Modules.Place.Domain.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("english_name");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_places_code");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_places_created_at");

                    b.HasIndex("Kind")
                        .HasDatabaseName("ix_places_kind");

                    b.ToTable("places", "place");
                });

            modelBuilder.Entity("TravelCore.Modules.Place.Domain.Restaurant", b =>
                {
                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("CuisineType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cuisine_type");

                    b.HasKey("PlaceId");

                    b.ToTable("restaurants", "place");
                });

            modelBuilder.Entity("TravelCore.Modules.Place.Domain.Attraction", b =>
                {
                    b.HasOne("TravelCore.Modules.Place.Domain.Place", null)
                        .WithOne("Attraction")
                        .HasForeignKey("TravelCore.Modules.Place.Domain.Attraction", "PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Place.Domain.Hotel", b =>
                {
                    b.HasOne("TravelCore.Modules.Place.Domain.Place", null)
                        .WithOne("Hotel")
                        .HasForeignKey("TravelCore.Modules.Place.Domain.Hotel", "PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Place.Domain.Restaurant", b =>
                {
                    b.HasOne("TravelCore.Modules.Place.Domain.Place", null)
                        .WithOne("Restaurant")
                        .HasForeignKey("TravelCore.Modules.Place.Domain.Restaurant", "PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCore.Modules.Place.Domain.Place", b =>
                {
                    b.Navigation("Attraction");

                    b.Navigation("Hotel");

                    b.Navigation("Restaurant");
                });
#pragma warning restore 612, 618
        }
    }
}
